/*
  Copyright (c) 1996 Blake McBride
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/


#include <stdio.h>

static	void	make_head(int m);
static	void	make_head2(int m);
static	void	run(int tab, int m, int n);
static	void	print_arg(int m);
static	void	make_tail(void);


main(int argc, char *argv[])
{
	int	i, m;
	
	if (argc == 2) {
		m = atoi(argv[1]);

		make_head(m);
		printf("\tswitch (argc) {\n");
		for (i=1 ; i <= m ; i++)
			run(2, i, 1);
		printf("\t}\n");
		printf("\treturn r;\n");
		printf("}\n\n");

		make_head2(m);
		printf("\tswitch (argc) {\n");
		for (i=1 ; i <= m ; i++)
			run(2, i, 1);
		printf("\t}\n");
		printf("\treturn r;\n");
		printf("}\n\n");

		make_tail();
	}
	return 0;
}

static	void	make_head(int m)
{
	printf("\n/*  This file is automatically generated by makevargs and should not normally\n");
	printf("    be edited by hand.  */\n\n");


	printf("#include \"generics.h\"\n");
	printf("#include \"scheme.h\"\n\n");

	printf("\n#define\tMAX_ARGS\t\t%d\n\n", m);
	printf("static\tobject\thandle_vargs4(int argc, Scheme_Object *argv[], ofun func, char *fun);\n");
	printf("static\tdouble\thandle_vargs8(int argc, Scheme_Object *argv[], double (*func)(), char *fun);\n");
	printf("static\tint\tget_arg(Scheme_Object *arg, long *f, double *e);\n\n");
	printf("#define\targ0\t(object) SCHEME_PTR_VAL(argv[0])\n\n");

	printf("Scheme_Object\t*handle_vargs_object(int argc, Scheme_Object *argv[], ofun func, char *fun)\n");
	printf("{\n");
	printf("\treturn scheme_new_dynace_object(handle_vargs4(argc, argv, func, fun));\n");
	printf("}\n\n");

	printf("Scheme_Object\t*handle_vargs_double(int argc, Scheme_Object *argv[], double (*func)(), char *fun)\n");
	printf("{\n");
	printf("\treturn scheme_make_double(handle_vargs8(argc, argv, func, fun));\n");
	printf("}\n\n");

	printf("Scheme_Object\t*handle_vargs_integer(int argc, Scheme_Object *argv[], int (*func)(), char *fun)\n");
	printf("{\n");
	printf("\treturn scheme_make_integer((int) handle_vargs4(argc, argv, (ofun) func, fun));\n");
	printf("}\n\n");

	printf("Scheme_Object\t*handle_vargs_c_pointer(int argc, Scheme_Object *argv[], ifun func, char *fun)\n");
	printf("{\n");
	printf("\treturn scheme_new_c_pointer((ifun) handle_vargs4(argc, argv, (ofun) func, fun));\n");
	printf("}\n\n");

	printf("Scheme_Object\t*handle_vargs_null(int argc, Scheme_Object *argv[], ifun func, char *fun)\n");
	printf("{\n");
	printf("\thandle_vargs4(argc, argv, (ofun) func, fun);\n");
	printf("\treturn scheme_null;\n");
	printf("}\n\n");

	printf("Scheme_Object\t*handle_vargs_string(int argc, Scheme_Object *argv[], char *(*func)(), char *fun)\n");
	printf("{\n");
	printf("\treturn scheme_make_string2((char *) handle_vargs4(argc, argv, (ofun) func, fun));\n");
	printf("}\n\n");

	printf("static\tobject\thandle_vargs4(int argc, Scheme_Object *argv[], ofun func, char *fun)\n");
	printf("{\n");
	printf("\tobject\tr = NULL;\n");
	printf("\tlong\tf[MAX_ARGS];\n");
	printf("\tdouble\te[MAX_ARGS];\n");
	printf("\tint\tt[MAX_ARGS], i;\n\n");

	printf("\tif (argc < 1  ||  argc > MAX_ARGS)\n");
	printf("\t\tscheme_wrong_count(fun, 1, MAX_ARGS, argc, argv);\n");
	printf("\tSCHEME_CHK_ARG_DYNACE(0);\n\n");

	printf("\tfor (i=1 ; i < argc && i < MAX_ARGS ; i++)\n");
	printf("\t\tt[i] = get_arg(argv[i], &f[i], &e[i]);\n\n");
}

static	void	make_head2(int m)
{
	printf("static\tdouble\thandle_vargs8(int argc, Scheme_Object *argv[], double (*func)(), char *fun)\n");

	printf("{\n");
	printf("\tdouble\tr = 0.0;\n");
	printf("\tlong\tf[MAX_ARGS];\n");
	printf("\tdouble\te[MAX_ARGS];\n");
	printf("\tint\tt[MAX_ARGS], i;\n\n");

	printf("\tif (argc < 1  ||  argc > MAX_ARGS)\n");
	printf("\t\tscheme_wrong_count(fun, 1, MAX_ARGS, argc, argv);\n");
	printf("\tSCHEME_CHK_ARG_DYNACE(0);\n\n");

	printf("\tfor (i=1 ; i < argc && i < MAX_ARGS ; i++)\n");
	printf("\t\tt[i] = get_arg(argv[i], &f[i], &e[i]);\n\n");
}


#define	TAB	for (t=0 ; t++ < tab ; )	printf("\t")

static	int	arg_state;

static	void	run(int tab, int m, int n)
{
	int	t;

	if (n == 1) {
		printf("\tcase %d:\n", m);
		arg_state = 0;
	}
	if (m == 1) {
		printf("\t");
		print_arg(m);
	} else {
		TAB;
		printf("if (t[%d] == 4) {\n", n);
		if (n < m-1)
			run(tab+1, m, n+1);
		else {
			TAB;
			print_arg(m);
		}
		TAB;
		printf("} else if (t[%d] == 8) {\n", n);
		if (n < m-1)
			run(tab+1, m, n+1);
		else {
			TAB;
			print_arg(m);
		}
		TAB;
		printf("}\n");
	}
	if (n == 1) {
		TAB;
		printf("break;\n");
	}
}

static	void	print_arg(int m)
{
	int	n = arg_state, w = m-1;
	int	i, tw=w;
	char	b[128];
	
	printf("\tr = func(arg0");
	for (i=w-1 ; n &&  i >= 0 ; n /= 2, w--)
		b[i--] = "fe"[n%2];
	while (w-- > 0  &&  i >= 0)
		b[i--] = 'f';
	for (i=1 ; i < m ; i++)
		printf(", %c[%d]", b[i-1], i);
	printf(");\n");
	arg_state++;
}

static	void	make_tail()
{
	printf("static\tint\tget_arg(Scheme_Object *arg, long *f, double *e)\n");
	printf("{\n");
	printf("\tif (SCHEME_DYNACEP(arg)  ||  SCHEME_CPOINTERP(arg)) {\n");
	printf("\t\t(void *) *f = SCHEME_PTR_VAL(arg);\n");
	printf("\t\treturn 4;\n");
	printf("\t} else if (SCHEME_INTP(arg)) {\n");
	printf("\t\t*f = SCHEME_INT_VAL(arg);\n");
	printf("\t\treturn 4;\n");
	printf("\t} else if (SCHEME_STRINGP(arg)) {\n");
	printf("\t\t(char *) *f = SCHEME_STR_VAL(arg);\n");
	printf("\t\treturn 4;\n");
	printf("\t} else if (SCHEME_DBLP(arg)) {\n");
	printf("\t\t*e = SCHEME_DBL_VAL(arg);\n");
	printf("\t\treturn 8;\n");
	printf("\t} else if (SCHEME_CHARP(arg)) {\n");
	printf("\t\t*f = SCHEME_CHAR_VAL(arg);\n");
	printf("\t\treturn 4;\n");
	printf("\t} else if (SCHEME_BOOLP(arg)) {\n");
	printf("\t\t*f = SCHEME_FALSEP(arg) ? 0 : 1;\n");
	printf("\t\treturn 4;\n");
	printf("\t}\n");
	printf("\treturn 0;\n");
	printf("}\n");
}
