/*
  Copyright (c) 1996 Blake McBride
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/



/*  This file automatically generated by dpp - do not edit  */

#define	DPP_STRATEGY	2
#define	DPP_FASTWIDE	0




#define	CLASS	Dynace_c
#define	ivType	Dynace_iv_t

#include "generics.h"

object	Dynace_c;


#line 34 "Dynace.d"
object SchemeClassSurrogate; 
object JavaScriptClassSurrogate; 
object JavaCallbackClassSurrogate; 


cmeth objrtn Dynace_cm_gTracePrint(object self, char *buf)
{ 
#ifndef __COSMIC__ 
	if (File_c) 
		gPuts(traceStream, buf); 
	else 
		printf("%s", buf); 
#endif 


#line 47 "Dynace.d"
	return self; 
} 

cmeth objrtn Dynace_cm_gObjectChecking(object self, int x)
{ 
	_CheckObjects_ = x; 
	if (!x) 
		_LastGeneric_ = NULL; 
	return self; 
} 

objrtn Dynace_initialize(void) 
{ 
	if (Dynace_c) 
		return Dynace_c; 

	Dynace_c = gNewClass(Class, "Dynace", 0, 0, END); 

	cMethodFor(Dynace, gTracePrint, Dynace_cm_gTracePrint); 
	cMethodFor(Dynace, gObjectChecking, Dynace_cm_gObjectChecking); 
	return Dynace_c; 
} 

#if 0 

cmeth objrtn Dynace_cm_gResizeMethodCache(object self, int classes, int generics){} 
cmeth objrtn Dynace_cm_gSetMemoryBufferArea(object self, long sz){} 
cmeth void Dynace_cm_gMarkRange(object self, char _HUGE_ **from, char _HUGE_ **to){} 
cmeth objrtn Dynace_cm_gGC(object self){} 
cmeth void * Dynace_cm_gRegisterMemory(object self, void *beg, long size){} 
cmeth void Dynace_cm_gRemoveRegisteredMemory(object self, void *pp){} 
cmeth void * Dynace_cm_gChangeRegisteredMemory(object self, void *pp, void *beg, long size){} 
cmeth long Dynace_cm_gMaxAfterGC(object self){} 
cmeth long Dynace_cm_gMaxMemUsed(object self){} 
cmeth long Dynace_cm_gCurMemUsed(object self){} 
cmeth long Dynace_cm_gNumbGC(object self){} 
cmeth int Dynace_cm_gTrace(object self, int mode){} 
cmeth void Dynace_cm_gMarkObject(object self, object obj){} 
cmeth objrtn Dynace_cm_gDumpObjects(object self, char *file, int type){} 
cmeth objrtn Dynace_cm_gDumpObjectsString(object self, int type){} 
cmeth objrtn Dynace_cm_gDumpObjectsDiff(object self, object sd1, object sd2){} 
cmeth objrtn Dynace_cm_gMarkMemoryBeginning(object self){} 
cmeth objrtn Dynace_cm_gDumpMemoryDiff(object self, object d1, char *fname){} 

#endif 

