
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 125
#define YY_END_OF_BUFFER 126
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[499] =
    {   0,
        0,    0,    0,    0,  126,  125,  123,  122,  125,  125,
      104,  104,  104,  104,  106,  100,   97,  101,  105,  105,
       16,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  125,  125,  119,  120,  123,   99,    0,  121,  116,
        0,  108,  106,    0,  108,    0,  107,    0,  102,   98,
      103,  105,  105,  105,  105,   11,  105,  105,  105,   15,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,   44,   50,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,   60,

       61,  105,   64,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,   85,
      105,  105,  105,  105,  105,  105,  105,  105,  105,    0,
        0,    0,  117,  119,    0,    0,  124,    0,  111,  107,
        0,    0,  109,    1,    2,    3,   10,   12,  105,    4,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
       37,  105,  105,  105,  105,  105,  105,  105,   48,  105,
       52,  105,  105,  105,    6,    5,  105,   57,  105,  105,
      105,  105,  105,  105,  105,   68,  105,  105,  105,  105,

      105,  105,  105,  105,  105,  105,   80,  105,  105,  105,
        7,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,    0,    0,    0,    0,  110,  105,  105,
       17,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,   29,  105,  105,   32,  105,  105,  105,
      105,  105,  105,   40,  105,  105,  105,  105,  105,  105,
      105,   49,   51,  105,   54,   55,  105,   58,  105,   62,
      105,  105,  105,  105,  105,  105,  105,  105,  105,   74,
      105,  105,  105,  105,  105,  105,   82,  105,  105,  105,
      105,  105,  105,  105,   90,  105,  105,   93,  105,   95,

       96,  118,    0,    0,  105,  105,  105,   18,   19,   20,
      105,    8,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,   35,   36,  105,  105,   41,   42,  105,
      105,   46,  105,  105,  105,  105,  105,  105,   65,   66,
      105,  105,  105,  105,  105,  105,  105,   76,  105,  105,
      105,  105,  105,  105,   84,  105,   87,  105,  105,  105,
      105,   94,    0,    0,  105,  105,  105,   21,   22,  105,
       24,  105,  105,  105,   28,  105,   31,   33,   34,  105,
      105,   43,  105,   47,  105,  105,   56,  105,   63,   67,
      105,  105,  105,  105,   73,  105,  105,   78,   79,  105,

      105,  105,  105,   88,   89,   91,  105,    0,    0,    0,
      105,   14,  105,   23,   25,   26,   27,  105,   38,   39,
      105,   48,  105,   59,  105,   70,  105,  105,  105,  105,
      105,   83,    9,   86,   92,    0,    0,    0,    0,  105,
      105,   30,  105,   53,  105,  105,  105,  105,   77,   81,
        0,    0,    0,    0,  105,   17,   45,   69,  105,   72,
      105,    0,    0,    0,  112,    0,  105,   71,   75,    0,
        0,  113,    0,  105,    0,    0,  105,    0,    0,   13,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  114,  115,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    1,    1,    1,    1,    7,    8,
        8,    8,    9,    8,   10,   11,    8,   12,   13,   13,
       12,   12,   12,   12,   12,   12,   12,   14,    8,   15,
       16,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
        1,    1,    1,    1,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,   65,   66,   67,   68,
       69,   70,   71,    1,   72,   73,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[74] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    1,    1,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        3,    3,    1
    } ;

static yyconst flex_int16_t yy_base[505] =
    {   0,
        0,    0,    3,    5,  174, 1178,   76, 1178,  156,   76,
     1178,   73,   80,   75,   83,   82, 1178,  138,  112,   60,
       75,   93,   67,  127,   76,   94,  122,   85,   96,  139,
      155,  131,  168,  175,    0,  183,  223,  189,  186,  209,
      234,   97,   93,    0, 1178,  193, 1178,  119,  164, 1178,
      261,  263,  278,  133,  282,  289,  284,  298, 1178, 1178,
     1178,    0,  184,  182,  282,  192,  186,  201,  219,    0,
      287,  281,  296,  292,  281,  299,  281,  280,  288,  301,
      297,  288,  297,  302,  306,  336,  300,  336,    0,  332,
      317,  329,  340,  341,  329,  340,  353,  338,  347,    0,

        0,  356,  358,  343,  346,  357,  386,  369,  393,  368,
      384,  389,  388,  403,  392,  394,  394,  390,  408,    0,
      402,  403,  409,  409,  407,  410,  411,  397,  402,  415,
       50,  453, 1178,    0,  464,  118, 1178,  265,  462,  466,
      471,  473,  477,    0,    0,    0,    0,    0,  443,    0,
      430,  437,  462,  451,  459,  462,  462,  476,  465,  476,
      478,  476,  483,  467,  487,  474,  490,  474,  491,  494,
      514,  483,  485,  479,  496,  515,  520,  523,  524,  516,
        0,  524,  513,  530,    0,    0,  515,    0,  525,  533,
      526,  532,  537,  538,  541,    0,  542,  537,  544,  536,

      537,  548,  546,  561,  573,  574,    0,  570,  578,  581,
        0,  581,  575,  581,  574,  589,  574,  572,  591,  572,
      578,  589,  587,  177,  606,  640,  608,  612,  598,  622,
      627,  618,  626,  620,  624,  614,  617,  633,  624,  628,
      641,  622,  624,    0,  636,  634,    0,  631,  628,  641,
      630,  642,  634,    0,  633,  641,  649,  664,  663,  664,
      676,    0,    0,  664,    0,    0,  674,    0,  669,    0,
      673,  671,  673,  691,  684,  694,  687,  692,  689,    0,
      681,  680,  699,  689,  700,  692,    0,  690,  705,  702,
      704,  703,  700,  715,    0,  731,  729,    0,  734,    0,

        0,  755,  746,  759,  728,  742,  747,    0,    0,    0,
      731,    0,  748,  740,  737,  755,  739,  746,  754,  746,
      756,  760,  748,    0,    0,  761,  768,    0,    0,  763,
      770,    0,  752,  771,  778,  784,  781,  777,    0,    0,
      781,  781,  783,  792,  801,  804,  803,    0,  808,  809,
      791,  803,  809,  794,    0,  810,    0,  814,  816,  803,
      822,    0,   91,  857,  815,  815,  810,    0,    0,  813,
        0,  832,  849,  835,    0,  855,    0,    0,    0,  845,
      847,    0,  842,    0,  845,  857,    0,  862,    0,    0,
      857,  842,  863,  848,    0,  856,  869,    0,    0,  859,

      869,  870,  858,    0,    0,    0,  859,  910,  921,  928,
      857,    0,  903,    0,    0,    0,    0,  892,    0,    0,
      898,    0,  910,    0,  904,    0,  913,  904,  922,  915,
      907,    0,    0,    0,    0,  941,  935,  955,  894,  931,
      915,    0,  916,    0,  924,  939,  943,  950,    0,    0,
      968,  206,  982,  993,  937,    0,    0,    0,  939,    0,
      948, 1004, 1007, 1015, 1178,  264,  960,    0,    0,  978,
      974, 1178, 1018,  965,  991, 1026,  976,  979, 1032,    0,
     1037, 1050, 1053, 1056, 1046, 1029, 1001, 1076, 1073, 1087,
     1084, 1090, 1058, 1069,   43, 1178, 1178, 1178, 1163, 1166,

      112, 1169, 1172, 1174
    } ;

static yyconst flex_int16_t yy_def[505] =
    {   0,
      498,    1,  499,  499,  498,  498,  498,  498,  498,  500,
      498,  498,  498,  498,  498,  498,  498,  498,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  498,  502,  503,  498,  498,  498,  500,  500,  498,
      500,  498,  498,  504,  498,  498,  498,  498,  498,  498,
      498,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,

      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  498,
      502,  502,  498,  503,  500,  504,  498,  498,  498,  498,
      498,  498,  498,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,

      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  498,  502,  500,  498,  498,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,

      501,  498,  502,  500,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  502,  500,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,

      501,  501,  501,  501,  501,  501,  501,  502,  500,  500,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  502,  502,  500,  500,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  501,  501,
      502,  502,  500,  500,  501,  501,  501,  501,  501,  501,
      501,  502,  502,  500,  498,  500,  501,  501,  501,  502,
      502,  498,  500,  501,  502,  500,  501,  502,  500,  501,
      502,  500,  500,  502,  502,  500,  502,  500,  502,  500,
      500,  502,  502,  500,  502,  498,  498,    0,  498,  498,

      498,  498,  498,  498
    } ;

static yyconst flex_int16_t yy_nxt[1252] =
    {   0,
        6,    7,    8,    7,    7,    9,   10,   11,   12,   13,
       14,   15,   15,   11,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       35,   35,   35,    6,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   35,   35,   35,
       42,    6,   43,   42,   45,   42,   45,   46,   49,   46,
       46,   69,   50,   52,   53,   53,   55,   55,   51,   54,
       52,   53,   53,   57,   53,   53,   56,   59,   60,   71,

      408,   70,   80,   72,   58,  132,   73,   81,   69,   74,
       86,   87,   75,   62,   76,  497,   90,   91,   77,  130,
      137,   49,  133,   56,   78,   50,   71,   79,   70,   80,
       72,   58,   63,   73,   81,  137,   74,   86,   87,   75,
       64,   76,   65,   90,   91,   77,  130,   66,   82,   67,
       68,   78,   88,   61,   79,   83,   92,   89,   84,   63,
       93,   85,   98,  133,   94,  133,   49,   64,   99,   65,
       50,   47,   95,  498,   66,   82,   67,   68,  302,   88,
       96,  302,   83,   92,   89,   84,   97,   93,   85,   98,
      100,   94,  105,  498,   46,   99,   46,   46,  101,   95,

      102,  144,  103,  106,  109,  104,  119,   96,  110,  107,
      145,  148,  108,   97,  111,  451,  122,  100,  123,  105,
      120,  124,  149,  121,  150,  101,  125,  102,  144,  103,
      106,  109,  104,  119,  126,  110,  107,  145,  148,  108,
      498,  111,  112,  122,  113,  123,  498,  120,  124,  149,
      121,  150,  114,  125,  115,  151,  116,  498,  127,  128,
      117,  126,  498,   49,  118,  129,   49,   50,  464,  112,
      465,  113,  135,  135,   55,   55,  139,  139,  133,  114,
      498,  115,  151,  116,   56,  127,  128,  117,   57,   53,
       53,  118,  129,   55,   55,  140,  140,  138,  138,   58,

      139,  139,  146,   56,  152,  141,  142,  142,  153,  143,
      143,   56,  154,  158,  155,  159,  164,  165,  160,  166,
      167,  161,  168,  147,  169,  156,   58,  162,  170,  146,
       56,  152,  141,  157,  163,  153,  171,  172,  175,  154,
      158,  155,  159,  164,  165,  160,  166,  167,  161,  168,
      147,  169,  156,  173,  162,  170,  176,  180,  181,  182,
      157,  163,  183,  171,  172,  175,  177,  174,  184,  185,
      186,  178,  179,  187,  188,  189,  190,  191,  193,  194,
      173,  195,  196,  176,  180,  181,  182,  200,  498,  183,
      498,  203,  192,  177,  174,  184,  185,  186,  178,  179,

      187,  188,  189,  190,  191,  193,  194,  197,  195,  196,
      201,  198,  204,  205,  200,  202,  206,  199,  203,  192,
      208,  209,  210,  211,  207,  212,  213,  214,  215,  216,
      217,  220,  221,  222,  197,  218,  223,  201,  198,  204,
      205,  219,  202,  206,  199,  224,  498,  208,  209,  210,
      211,  207,  212,  213,  214,  215,  216,  217,  220,  221,
      222,  498,  218,  223,  225,  225,   49,  229,  219,  230,
       50,  231,  224,  139,  139,  226,  226,  140,  140,  227,
      227,  232,  228,  228,  143,  143,  233,  141,  143,  143,
      234,  235,  236,  237,  229,  242,  230,  243,  231,  238,

      239,  240,  244,  245,  241,  246,  247,  248,  232,  249,
      250,  251,  254,  233,  141,  255,  256,  234,  235,  236,
      237,  257,  242,  498,  243,  133,  238,  239,  240,  244,
      245,  241,  246,  247,  248,  252,  249,  250,  251,  254,
      258,  259,  255,  256,  260,  261,  263,  264,  257,  265,
      253,  266,  267,  268,  269,  262,  270,  271,  272,  273,
      274,  275,  252,  278,  279,  280,  276,  258,  259,  281,
      282,  260,  261,  263,  264,  277,  265,  253,  266,  267,
      268,  269,  262,  270,  271,  272,  273,  274,  275,  283,
      278,  279,  280,  276,  284,  285,  281,  282,  286,  287,

      288,  289,  277,  290,  291,  292,  294,  293,  295,  296,
      297,  298,  299,  300,  301,  498,  283,  303,  303,  228,
      228,  284,  285,  228,  228,  286,  287,  288,  289,  305,
      290,  291,  292,  294,  293,  295,  296,  297,  298,  299,
      300,  301,   49,  306,  307,  308,   50,  309,  310,  311,
      312,  304,  304,  313,  314,  315,  305,  316,  317,  318,
      319,  320,  321,  322,  323,  324,  325,  326,  327,  328,
      306,  307,  308,  329,  309,  310,  311,  312,  133,  330,
      313,  314,  315,  331,  316,  317,  318,  319,  320,  321,
      322,  323,  324,  325,  326,  327,  328,  332,  333,  334,

      329,  335,  336,  337,  338,  339,  330,  340,  341,  342,
      331,  343,  344,  345,  346,  347,  348,  349,  350,  351,
      352,  353,  354,  355,  332,  333,  334,  356,  335,  336,
      337,  338,  339,  357,  340,  341,  342,  358,  343,  344,
      345,  346,  347,  348,  349,  350,  351,  352,  353,  354,
      355,  359,  360,  361,  356,  362,  302,  363,  363,  302,
      357,   49,  365,  366,  358,   50,  367,  368,  364,  369,
      370,  371,  372,  373,  374,  375,  376,  377,  359,  360,
      361,  378,  362,  379,  380,  381,  382,  383,  384,  365,
      366,  498,  385,  367,  368,  386,  369,  370,  371,  372,

      373,  374,  375,  376,  377,  387,  388,  389,  378,  390,
      379,  380,  381,  382,  383,  384,  391,  392,  133,  385,
      393,  394,  386,  395,  396,  397,  398,  399,  400,  401,
      402,  403,  387,  388,  389,  404,  390,  405,  406,  407,
      411,  498,  498,  391,  392,  412,  413,  393,  394,  414,
      395,  396,  397,  398,  399,  400,  401,  402,  403,   49,
      415,  409,  404,   50,  405,  406,  407,  411,  410,  410,
      416,  417,  412,  413,  418,  419,  414,  420,  421,  422,
      423,  424,  425,  426,  427,  428,  429,  415,  430,  431,
      432,  433,  434,  435,  498,  498,   49,  416,  417,  440,

       50,  418,  419,  438,  420,  421,  422,  423,  424,  425,
      426,  427,  428,  429,  436,  430,  431,  432,  433,  434,
      435,  437,  437,   49,  441,  409,  440,   50,  442,  443,
       49,  444,  410,  410,   50,  445,  446,  438,  447,  439,
      439,  448,  449,  450,  451,  436,  452,  452,  455,  456,
      457,  441,  437,  437,  458,  442,  443,   49,  444,  453,
      459,   50,  445,  446,  460,  447,  454,  454,  448,  449,
      450,  461,  462,  467,  468,  455,  456,  457,  470,  463,
      463,  458,  133,  469,   49,  474,  453,  459,   50,  475,
      475,  460,  481,  454,  454,   49,  477,  464,  461,  465,

      467,  468,  478,  478,  466,  466,  480,  133,  462,  498,
      469,  470,  474,  133,  489,  463,  463,   49,  471,  471,
       49,   50,  498,  477,   50,  498,  473,  473,   49,  476,
      476,   49,   50,  480,   49,   50,  482,  498,   50,  479,
      133,  484,  488,  483,  483,  498,  472,  498,  485,  485,
      133,  133,   49,  498,  482,   49,   50,  487,  487,   50,
      484,  483,  483,  133,  486,  486,  498,  485,  485,  495,
      495,   49,  498,  133,  498,  496,  133,  492,   49,  472,
      490,  498,   50,  498,  493,  493,   49,  491,  491,   49,
       50,  490,  498,   50,  492,  494,  494,  498,  491,  491,

      498,  493,  493,  498,  498,  498,  498,  498,  498,  133,
      498,  498,  498,  498,  498,  498,  498,  498,  133,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  133,  498,
      133,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  133,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  133,   44,   44,   44,   48,   48,   48,  131,
      131,  131,  134,  134,  136,  136,  136,    5,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,

      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498
    } ;

static yyconst flex_int16_t yy_chk[1252] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    4,    4,    7,   10,    7,
        7,   20,   10,   12,   12,   12,   14,   14,   10,   13,
       13,   13,   13,   15,   15,   15,   14,   16,   16,   21,

      363,   20,   23,   21,   15,   43,   21,   23,   20,   21,
       25,   26,   21,  501,   22,  495,   28,   29,   22,   42,
      136,   48,  131,   14,   22,   48,   21,   22,   20,   23,
       21,   15,   19,   21,   23,   54,   21,   25,   26,   21,
       19,   22,   19,   28,   29,   22,   42,   19,   24,   19,
       19,   22,   27,   18,   22,   24,   30,   27,   24,   19,
       30,   24,   32,  363,   30,   43,   49,   19,   32,   19,
       49,    9,   31,    5,   19,   24,   19,   19,  224,   27,
       31,  224,   24,   30,   27,   24,   31,   30,   24,   32,
       33,   30,   34,    0,   46,   32,   46,   46,   33,   31,

       33,   63,   33,   34,   36,   33,   38,   31,   36,   34,
       64,   66,   34,   31,   36,  452,   39,   33,   39,   34,
       38,   39,   67,   38,   68,   33,   40,   33,   63,   33,
       34,   36,   33,   38,   40,   36,   34,   64,   66,   34,
        0,   36,   37,   39,   37,   39,    0,   38,   39,   67,
       38,   68,   37,   40,   37,   69,   37,    0,   41,   41,
       37,   40,    0,   51,   37,   41,  466,   51,  466,   37,
      466,   37,   51,   51,   52,   52,  138,  138,  452,   37,
        0,   37,   69,   37,   52,   41,   41,   37,   53,   53,
       53,   37,   41,   55,   55,   57,   57,   56,   56,   53,

       56,   56,   65,   55,   71,   57,   58,   58,   71,   58,
       58,   52,   72,   74,   73,   75,   77,   78,   76,   79,
       80,   76,   81,   65,   82,   73,   53,   76,   83,   65,
       55,   71,   57,   73,   76,   71,   84,   85,   87,   72,
       74,   73,   75,   77,   78,   76,   79,   80,   76,   81,
       65,   82,   73,   86,   76,   83,   88,   90,   91,   92,
       73,   76,   93,   84,   85,   87,   88,   86,   94,   95,
       96,   88,   88,   97,   98,   99,   99,  102,  103,  104,
       86,  105,  106,   88,   90,   91,   92,  108,    0,   93,
        0,  110,  102,   88,   86,   94,   95,   96,   88,   88,

       97,   98,   99,   99,  102,  103,  104,  107,  105,  106,
      109,  107,  111,  112,  108,  109,  113,  107,  110,  102,
      114,  115,  116,  117,  113,  118,  119,  121,  122,  123,
      124,  126,  127,  128,  107,  125,  129,  109,  107,  111,
      112,  125,  109,  113,  107,  130,    0,  114,  115,  116,
      117,  113,  118,  119,  121,  122,  123,  124,  126,  127,
      128,    0,  125,  129,  132,  132,  135,  149,  125,  151,
      135,  152,  130,  139,  139,  135,  135,  140,  140,  141,
      141,  153,  141,  141,  142,  142,  154,  140,  143,  143,
      155,  156,  157,  158,  149,  161,  151,  162,  152,  159,

      159,  160,  163,  164,  160,  165,  166,  167,  153,  168,
      169,  170,  172,  154,  140,  173,  174,  155,  156,  157,
      158,  175,  161,    0,  162,  132,  159,  159,  160,  163,
      164,  160,  165,  166,  167,  171,  168,  169,  170,  172,
      176,  177,  173,  174,  178,  179,  180,  182,  175,  183,
      171,  184,  187,  189,  190,  179,  191,  192,  193,  194,
      195,  197,  171,  199,  200,  201,  198,  176,  177,  202,
      203,  178,  179,  180,  182,  198,  183,  171,  184,  187,
      189,  190,  179,  191,  192,  193,  194,  195,  197,  204,
      199,  200,  201,  198,  205,  206,  202,  203,  208,  209,

      210,  212,  198,  213,  214,  215,  216,  215,  217,  218,
      219,  220,  221,  222,  223,    0,  204,  225,  225,  227,
      227,  205,  206,  228,  228,  208,  209,  210,  212,  229,
      213,  214,  215,  216,  215,  217,  218,  219,  220,  221,
      222,  223,  226,  230,  231,  232,  226,  233,  234,  235,
      236,  226,  226,  237,  238,  239,  229,  240,  241,  242,
      243,  245,  246,  248,  249,  250,  251,  252,  253,  255,
      230,  231,  232,  256,  233,  234,  235,  236,  225,  257,
      237,  238,  239,  258,  240,  241,  242,  243,  245,  246,
      248,  249,  250,  251,  252,  253,  255,  259,  260,  261,

      256,  264,  267,  269,  271,  272,  257,  273,  274,  275,
      258,  276,  277,  278,  279,  281,  282,  283,  284,  285,
      286,  288,  289,  290,  259,  260,  261,  291,  264,  267,
      269,  271,  272,  292,  273,  274,  275,  293,  276,  277,
      278,  279,  281,  282,  283,  284,  285,  286,  288,  289,
      290,  294,  296,  297,  291,  299,  302,  303,  303,  302,
      292,  304,  305,  306,  293,  304,  307,  311,  304,  313,
      314,  315,  316,  317,  318,  319,  320,  321,  294,  296,
      297,  322,  299,  323,  326,  327,  330,  331,  333,  305,
      306,    0,  334,  307,  311,  335,  313,  314,  315,  316,

      317,  318,  319,  320,  321,  336,  337,  338,  322,  341,
      323,  326,  327,  330,  331,  333,  342,  343,  303,  334,
      344,  345,  335,  346,  347,  349,  350,  351,  352,  353,
      354,  356,  336,  337,  338,  358,  341,  359,  360,  361,
      365,    0,    0,  342,  343,  366,  367,  344,  345,  370,
      346,  347,  349,  350,  351,  352,  353,  354,  356,  364,
      372,  364,  358,  364,  359,  360,  361,  365,  364,  364,
      373,  374,  366,  367,  376,  380,  370,  381,  383,  385,
      386,  388,  391,  392,  393,  394,  396,  372,  397,  400,
      401,  402,  403,  407,    0,    0,  439,  373,  374,  411,

      439,  376,  380,  439,  381,  383,  385,  386,  388,  391,
      392,  393,  394,  396,  408,  397,  400,  401,  402,  403,
      407,  408,  408,  409,  413,  409,  411,  409,  418,  421,
      410,  423,  409,  409,  410,  425,  427,  410,  428,  410,
      410,  429,  430,  431,  437,  436,  437,  437,  440,  441,
      443,  413,  436,  436,  445,  418,  421,  438,  423,  438,
      446,  438,  425,  427,  447,  428,  438,  438,  429,  430,
      431,  448,  451,  455,  459,  440,  441,  443,  471,  451,
      451,  445,  408,  461,  453,  467,  453,  446,  453,  470,
      470,  447,  478,  453,  453,  454,  474,  454,  448,  454,

      455,  459,  475,  475,  454,  454,  477,  437,  462,    0,
      461,  463,  467,  436,  487,  462,  462,  464,  463,  463,
      473,  464,    0,  474,  473,    0,  464,  464,  476,  473,
      473,  486,  476,  477,  479,  486,  479,    0,  479,  476,
      451,  481,  486,  479,  479,    0,  471,    0,  481,  481,
      470,  478,  482,    0,  482,  483,  482,  485,  485,  483,
      484,  482,  482,  475,  483,  483,    0,  484,  484,  493,
      493,  494,    0,  487,    0,  494,  462,  489,  488,  463,
      488,    0,  488,    0,  489,  489,  491,  488,  488,  490,
      491,  490,    0,  490,  492,  491,  491,    0,  490,  490,

        0,  492,  492,    0,    0,    0,    0,    0,    0,  481,
        0,    0,    0,    0,    0,    0,    0,    0,  485,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  484,    0,
      493,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  489,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  492,  499,  499,  499,  500,  500,  500,  502,
      502,  502,  503,  503,  504,  504,  504,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,

      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  498,  498,  498,
      498
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sqltokens.l"
#line 2 "sqltokens.l"


#include "sqlgrammar.h"
#include "sqlstructs.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

#pragma warning (disable:4013)

int sql_lineno = 1;
void yyerror(void *, char *s);
int nesting_level = 0;
extern void *  __sql_alloc(size_t size);
/* MKS needs the next line to increase the NFA table */

#line 923 "lex.yy.c"

#define INITIAL 0
#define ODBCFUNC 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 22 "sqltokens.l"


	/* literal keyword tokens */

#line 1116 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 499 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1178 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "sqltokens.l"
{ return ADA; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 27 "sqltokens.l"
{ return ALL; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 28 "sqltokens.l"
{ return AND; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 29 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE) str;
			return AMMSC;
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 34 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE) str;
			return AMMSC;
		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE) str;
			return AMMSC;
		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE) str;
			return AMMSC;
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE) str;
			return AMMSC;
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 54 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE) str;
			return AMMSC;
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "sqltokens.l"
{ return ANY; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "sqltokens.l"
{ return AS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "sqltokens.l"
{ return ASC; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "sqltokens.l"
{ return AUTHORIZATION; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "sqltokens.l"
{ return BETWEEN; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "sqltokens.l"
{ return BY; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "sqltokens.l"
{ return C; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "sqltokens.l"
{ return CHARACTER; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "sqltokens.l"
{ return CHECK; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "sqltokens.l"
{ return CLOSE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "sqltokens.l"
{ return COBOL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "sqltokens.l"
{ return COMMIT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "sqltokens.l"
{ return CREATE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "sqltokens.l"
{ return CURRENT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "sqltokens.l"
{ return CURSOR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "sqltokens.l"
{ return DECIMAL2; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "sqltokens.l"
{ return DECLARE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "sqltokens.l"
{ return DEFAULT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "sqltokens.l"
{ return DELETE2; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "sqltokens.l"
{ return DESC; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 80 "sqltokens.l"
{ return DISTINCT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 81 "sqltokens.l"
{ return DOUBLE2; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "sqltokens.l"
{ return DROP; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 83 "sqltokens.l"
{ return ESCAPE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 84 "sqltokens.l"
{ return EXISTS; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 85 "sqltokens.l"
{ return FETCH; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 86 "sqltokens.l"
{ return FLOAT2; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "sqltokens.l"
{ return FOR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 88 "sqltokens.l"
{ return FOREIGN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 89 "sqltokens.l"
{ return FORTRAN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "sqltokens.l"
{ return FROM; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 91 "sqltokens.l"
{ return GRANT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "sqltokens.l"
{ return GROUP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "sqltokens.l"
{ return HAVING; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 94 "sqltokens.l"
{ return IN2; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 95 "sqltokens.l"
{ return INDICATOR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 96 "sqltokens.l"
{ return INNER; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 97 "sqltokens.l"
{ return INSERT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 98 "sqltokens.l"
{ return INTEGER; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 99 "sqltokens.l"
{ return INTO; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 100 "sqltokens.l"
{ return IS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 101 "sqltokens.l"
{ return JOIN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 "sqltokens.l"
{ return KEY; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 103 "sqltokens.l"
{ return LANGUAGE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 104 "sqltokens.l"
{ return LEFT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 105 "sqltokens.l"
{ return LIKE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 106 "sqltokens.l"
{ return MODULE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 107 "sqltokens.l"
{ return NOT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 108 "sqltokens.l"
{ return NULLX; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 109 "sqltokens.l"
{ return NUMERIC; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 110 "sqltokens.l"
{ return OF; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 111 "sqltokens.l"
{ return ON; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 112 "sqltokens.l"
{ return OPEN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 113 "sqltokens.l"
{ return OPTION; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 114 "sqltokens.l"
{ return OR; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 115 "sqltokens.l"
{ return ORDER; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 116 "sqltokens.l"
{ return OUTER; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 117 "sqltokens.l"
{ return PASCAL2; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 118 "sqltokens.l"
{ return PLI; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 119 "sqltokens.l"
{ return PRECISION; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 120 "sqltokens.l"
{ return PRIMARY; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 121 "sqltokens.l"
{ return PRIVILEGES; }	
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 122 "sqltokens.l"
{ return PROCEDURE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 123 "sqltokens.l"
{ return PUBLIC; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 124 "sqltokens.l"
{ return REAL; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 125 "sqltokens.l"
{ return REFERENCES; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 126 "sqltokens.l"
{ return RIGHT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 127 "sqltokens.l"
{ return ROLLBACK; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 128 "sqltokens.l"
{ return SCHEMA; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 129 "sqltokens.l"
{ return SELECT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 130 "sqltokens.l"
{ return SET; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 131 "sqltokens.l"
{ return SMALLINT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 132 "sqltokens.l"
{ return SOME; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 133 "sqltokens.l"
{ return SQLCODE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 134 "sqltokens.l"
{ return TABLE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 135 "sqltokens.l"
{ return TO; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 136 "sqltokens.l"
{ return TRIGGER; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 137 "sqltokens.l"
{ return UNION; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 138 "sqltokens.l"
{ return UNIQUE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 139 "sqltokens.l"
{ return UPDATE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 140 "sqltokens.l"
{ return USER; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 141 "sqltokens.l"
{ return VALUES; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 142 "sqltokens.l"
{ return VARCHAR; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 143 "sqltokens.l"
{ return VIEW; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 144 "sqltokens.l"
{ return WHERE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 145 "sqltokens.l"
{ return WITH; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 146 "sqltokens.l"
{ return WORK; }
	YY_BREAK
/* punctuation */
case 97:
YY_RULE_SETUP
#line 150 "sqltokens.l"
{ 
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return EQUALS; 
		}
	YY_BREAK
case 98:
#line 157 "sqltokens.l"
case 99:
YY_RULE_SETUP
#line 157 "sqltokens.l"
{ 
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return NOT_EQUALS; 
		}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 163 "sqltokens.l"
{ 
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return LESS_THAN; 
		}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 169 "sqltokens.l"
{ 
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return GREATER_THAN; 
		}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 175 "sqltokens.l"
{ 
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return LESS_THAN_EQ; 
		}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 181 "sqltokens.l"
{ 
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return GREATER_THAN_EQ; 
		}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 187 "sqltokens.l"
{ 
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return yytext[0]; 
		}
	YY_BREAK
/* names */
case 105:
YY_RULE_SETUP
#line 195 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return NAME;
		}
	YY_BREAK
/* numbers */
case 106:
YY_RULE_SETUP
#line 203 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return INTNUM;
 		}
	YY_BREAK
case 107:
#line 210 "sqltokens.l"
case 108:
#line 211 "sqltokens.l"
case 109:
#line 212 "sqltokens.l"
case 110:
#line 213 "sqltokens.l"
case 111:
YY_RULE_SETUP
#line 213 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return APPROXNUM;
 		}
	YY_BREAK
/* strings */
case 112:
#line 222 "sqltokens.l"
case 113:
YY_RULE_SETUP
#line 222 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return DATE_LITERAL;
		}
	YY_BREAK
case 114:
#line 229 "sqltokens.l"
case 115:
YY_RULE_SETUP
#line 229 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return TIME_LITERAL;
		}
	YY_BREAK
case 116:
/* rule 116 can match eol */
#line 236 "sqltokens.l"
case 117:
/* rule 117 can match eol */
YY_RULE_SETUP
#line 236 "sqltokens.l"
{
			char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
			yylval = (YYSTYPE)str;
			return STRING;
		}
	YY_BREAK
/* treat ODBC scalar function calls as string literals (these functions can nest) */
case 118:
YY_RULE_SETUP
#line 244 "sqltokens.l"
{
			if (! nesting_level++)
				BEGIN(ODBCFUNC);
			yymore();
		}
	YY_BREAK
case 119:
/* rule 119 can match eol */
YY_RULE_SETUP
#line 250 "sqltokens.l"
{
			yymore();
		}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 254 "sqltokens.l"
{
			if (--nesting_level)
				yymore();
			else {
				char	*str = strcpy((char*)__sql_alloc(strlen(yytext) + 1), yytext);
				yylval = (YYSTYPE)str;
				BEGIN(INITIAL);
				return STRING;
			}
		}
	YY_BREAK
case 121:
/* rule 121 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 266 "sqltokens.l"
{ 
			yyerror(NULL, "Unterminated string"); 
		}
	YY_BREAK
case 122:
/* rule 122 can match eol */
YY_RULE_SETUP
#line 270 "sqltokens.l"
{
			sql_lineno++;
		}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 274 "sqltokens.l"
;	/* white space */
	YY_BREAK
case 124:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 276 "sqltokens.l"
;	/* comment */
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 278 "sqltokens.l"
ECHO;
	YY_BREAK
#line 1917 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ODBCFUNC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 499 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 499 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 498);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 278 "sqltokens.l"



