/*
  Copyright (c) 1996 Blake McBride
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/



/*  This file is automatically generated by dpp and should not normally
    be edited by hand.  */


#ifndef	_GENERICS_H
#define	_GENERICS_H


#ifdef	DPP_STRATEGY
#if	DPP_STRATEGY != 2
#error Incompatible DPP Strategies
#endif
#else
#define	DPP_STRATEGY 2
#endif

#ifdef	DPP_FASTWIDE
#if	DPP_FASTWIDE != 0
#error Incompatible DPP FastWide Status
#endif
#else
#define	DPP_FASTWIDE 0
#endif

#include "dynl.h"


#ifdef	__cplusplus
extern	"C"  {
#endif




#undef	START_CLASSES

extern	object	Abort_c;
extern	object	Array_c;
extern	object	Association_c;
extern	object	BTree_c;
extern	object	BTreeNode_c;
extern	object	Behavior_c;
extern	object	BitArray_c;
extern	object	BufferedTempFile_c;
extern	object	Character_c;
extern	object	CharacterArray_c;
extern	object	Class_c;
extern	object	Condition_c;
extern	object	Constant_c;
extern	object	Date_c;
extern	object	DateTime_c;
extern	object	Dictionary_c;
extern	object	DoubleFloat_c;
extern	object	DoubleFloatArray_c;
extern	object	Dynace_c;
extern	object	Error_c;
extern	object	File_c;
extern	object	FindFile_c;
extern	object	FloatArray_c;
extern	object	GenericFunction_c;
extern	object	IntegerArray_c;
extern	object	IntegerAssociation_c;
extern	object	IntegerDictionary_c;
extern	object	Link_c;
extern	object	LinkList_c;
extern	object	LinkObject_c;
extern	object	LinkObjectSequence_c;
extern	object	LinkSequence_c;
extern	object	LinkValue_c;
extern	object	LongArray_c;
extern	object	LongInteger_c;
extern	object	LookupKey_c;
extern	object	LowFile_c;
extern	object	Memory_c;
extern	object	MetaClass_c;
extern	object	Method_c;
extern	object	MimeBodyPart_c;
extern	object	MultipartMime_c;
extern	object	Number_c;
extern	object	NumberArray_c;
extern	object	Object_c;
extern	object	ObjectArray_c;
extern	object	ObjectAssociation_c;
extern	object	ObjectPool_c;
extern	object	Pipe_c;
extern	object	Pointer_c;
extern	object	PointerArray_c;
extern	object	PropertyList_c;
extern	object	Restart_c;
extern	object	Semaphore_c;
extern	object	Sequence_c;
extern	object	SeriousCondition_c;
extern	object	Set_c;
extern	object	SetSequence_c;
extern	object	ShortArray_c;
extern	object	ShortInteger_c;
extern	object	SimpleRestart_c;
extern	object	SimpleWarning_c;
extern	object	Socket_c;
extern	object	Stream_c;
extern	object	String_c;
extern	object	StringAssociation_c;
extern	object	StringDictionary_c;
extern	object	Thread_c;
extern	object	Time_c;
extern	object	UnsignedShortArray_c;
extern	object	UnsignedShortInteger_c;
extern	object	Warning_c;
extern	object	WeakPointer_c;
extern	object	XMLNode_c;

#undef	END_CLASSES


extern	objrtn	Abort_initialize(void);
extern	objrtn	Array_initialize(void);
extern	objrtn	Association_initialize(void);
extern	objrtn	BTree_initialize(void);
extern	objrtn	BTreeNode_initialize(void);
extern	objrtn	Behavior_initialize(void);
extern	objrtn	BitArray_initialize(void);
extern	objrtn	BufferedTempFile_initialize(void);
extern	objrtn	Character_initialize(void);
extern	objrtn	CharacterArray_initialize(void);
extern	objrtn	Class_initialize(void);
extern	objrtn	Condition_initialize(void);
extern	objrtn	Constant_initialize(void);
extern	objrtn	Date_initialize(void);
extern	objrtn	DateTime_initialize(void);
extern	objrtn	Dictionary_initialize(void);
extern	objrtn	DoubleFloat_initialize(void);
extern	objrtn	DoubleFloatArray_initialize(void);
extern	objrtn	Dynace_initialize(void);
extern	objrtn	Error_initialize(void);
extern	objrtn	File_initialize(void);
extern	objrtn	FindFile_initialize(void);
extern	objrtn	FloatArray_initialize(void);
extern	objrtn	GenericFunction_initialize(void);
extern	objrtn	IntegerArray_initialize(void);
extern	objrtn	IntegerAssociation_initialize(void);
extern	objrtn	IntegerDictionary_initialize(void);
extern	objrtn	Link_initialize(void);
extern	objrtn	LinkList_initialize(void);
extern	objrtn	LinkObject_initialize(void);
extern	objrtn	LinkObjectSequence_initialize(void);
extern	objrtn	LinkSequence_initialize(void);
extern	objrtn	LinkValue_initialize(void);
extern	objrtn	LongArray_initialize(void);
extern	objrtn	LongInteger_initialize(void);
extern	objrtn	LookupKey_initialize(void);
extern	objrtn	LowFile_initialize(void);
extern	objrtn	Memory_initialize(void);
extern	objrtn	MetaClass_initialize(void);
extern	objrtn	Method_initialize(void);
extern	objrtn	MimeBodyPart_initialize(void);
extern	objrtn	MultipartMime_initialize(void);
extern	objrtn	Number_initialize(void);
extern	objrtn	NumberArray_initialize(void);
extern	objrtn	Object_initialize(void);
extern	objrtn	ObjectArray_initialize(void);
extern	objrtn	ObjectAssociation_initialize(void);
extern	objrtn	ObjectPool_initialize(void);
extern	objrtn	Pipe_initialize(void);
extern	objrtn	Pointer_initialize(void);
extern	objrtn	PointerArray_initialize(void);
extern	objrtn	PropertyList_initialize(void);
extern	objrtn	Restart_initialize(void);
extern	objrtn	Semaphore_initialize(void);
extern	objrtn	Sequence_initialize(void);
extern	objrtn	SeriousCondition_initialize(void);
extern	objrtn	Set_initialize(void);
extern	objrtn	SetSequence_initialize(void);
extern	objrtn	ShortArray_initialize(void);
extern	objrtn	ShortInteger_initialize(void);
extern	objrtn	SimpleRestart_initialize(void);
extern	objrtn	SimpleWarning_initialize(void);
extern	objrtn	Socket_initialize(void);
extern	objrtn	Stream_initialize(void);
extern	objrtn	String_initialize(void);
extern	objrtn	StringAssociation_initialize(void);
extern	objrtn	StringDictionary_initialize(void);
extern	objrtn	Thread_initialize(void);
extern	objrtn	Time_initialize(void);
extern	objrtn	UnsignedShortArray_initialize(void);
extern	objrtn	UnsignedShortInteger_initialize(void);
extern	objrtn	Warning_initialize(void);
extern	objrtn	WeakPointer_initialize(void);
extern	objrtn	XMLNode_initialize(void);



#define	Abort	(Abort_c ? Abort_c : Abort_initialize())
#define	Array	(Array_c ? Array_c : Array_initialize())
#define	Association	(Association_c ? Association_c : Association_initialize())
#define	BTree	(BTree_c ? BTree_c : BTree_initialize())
#define	BTreeNode	(BTreeNode_c ? BTreeNode_c : BTreeNode_initialize())
#define	Behavior	(Behavior_c ? Behavior_c : Behavior_initialize())
#define	BitArray	(BitArray_c ? BitArray_c : BitArray_initialize())
#define	BufferedTempFile	(BufferedTempFile_c ? BufferedTempFile_c : BufferedTempFile_initialize())
#define	Character	(Character_c ? Character_c : Character_initialize())
#define	CharacterArray	(CharacterArray_c ? CharacterArray_c : CharacterArray_initialize())
#define	Class	(Class_c ? Class_c : Class_initialize())
#define	Condition	(Condition_c ? Condition_c : Condition_initialize())
#define	Constant	(Constant_c ? Constant_c : Constant_initialize())
#define	Date	(Date_c ? Date_c : Date_initialize())
#define	DateTime	(DateTime_c ? DateTime_c : DateTime_initialize())
#define	Dictionary	(Dictionary_c ? Dictionary_c : Dictionary_initialize())
#define	DoubleFloat	(DoubleFloat_c ? DoubleFloat_c : DoubleFloat_initialize())
#define	DoubleFloatArray	(DoubleFloatArray_c ? DoubleFloatArray_c : DoubleFloatArray_initialize())
#define	Dynace	(Dynace_c ? Dynace_c : Dynace_initialize())
#define	Error	(Error_c ? Error_c : Error_initialize())
#define	File	(File_c ? File_c : File_initialize())
#define	FindFile	(FindFile_c ? FindFile_c : FindFile_initialize())
#define	FloatArray	(FloatArray_c ? FloatArray_c : FloatArray_initialize())
#define	GenericFunction	(GenericFunction_c ? GenericFunction_c : GenericFunction_initialize())
#define	IntegerArray	(IntegerArray_c ? IntegerArray_c : IntegerArray_initialize())
#define	IntegerAssociation	(IntegerAssociation_c ? IntegerAssociation_c : IntegerAssociation_initialize())
#define	IntegerDictionary	(IntegerDictionary_c ? IntegerDictionary_c : IntegerDictionary_initialize())
#define	Link	(Link_c ? Link_c : Link_initialize())
#define	LinkList	(LinkList_c ? LinkList_c : LinkList_initialize())
#define	LinkObject	(LinkObject_c ? LinkObject_c : LinkObject_initialize())
#define	LinkObjectSequence	(LinkObjectSequence_c ? LinkObjectSequence_c : LinkObjectSequence_initialize())
#define	LinkSequence	(LinkSequence_c ? LinkSequence_c : LinkSequence_initialize())
#define	LinkValue	(LinkValue_c ? LinkValue_c : LinkValue_initialize())
#define	LongArray	(LongArray_c ? LongArray_c : LongArray_initialize())
#define	LongInteger	(LongInteger_c ? LongInteger_c : LongInteger_initialize())
#define	LookupKey	(LookupKey_c ? LookupKey_c : LookupKey_initialize())
#define	LowFile	(LowFile_c ? LowFile_c : LowFile_initialize())
#define	Memory	(Memory_c ? Memory_c : Memory_initialize())
#define	MetaClass	(MetaClass_c ? MetaClass_c : MetaClass_initialize())
#define	Method	(Method_c ? Method_c : Method_initialize())
#define	MimeBodyPart	(MimeBodyPart_c ? MimeBodyPart_c : MimeBodyPart_initialize())
#define	MultipartMime	(MultipartMime_c ? MultipartMime_c : MultipartMime_initialize())
#define	Number	(Number_c ? Number_c : Number_initialize())
#define	NumberArray	(NumberArray_c ? NumberArray_c : NumberArray_initialize())
#define	Object	(Object_c ? Object_c : Object_initialize())
#define	ObjectArray	(ObjectArray_c ? ObjectArray_c : ObjectArray_initialize())
#define	ObjectAssociation	(ObjectAssociation_c ? ObjectAssociation_c : ObjectAssociation_initialize())
#define	ObjectPool	(ObjectPool_c ? ObjectPool_c : ObjectPool_initialize())
#define	Pipe	(Pipe_c ? Pipe_c : Pipe_initialize())
#define	Pointer	(Pointer_c ? Pointer_c : Pointer_initialize())
#define	PointerArray	(PointerArray_c ? PointerArray_c : PointerArray_initialize())
#define	PropertyList	(PropertyList_c ? PropertyList_c : PropertyList_initialize())
#define	Restart	(Restart_c ? Restart_c : Restart_initialize())
#define	Semaphore	(Semaphore_c ? Semaphore_c : Semaphore_initialize())
#define	Sequence	(Sequence_c ? Sequence_c : Sequence_initialize())
#define	SeriousCondition	(SeriousCondition_c ? SeriousCondition_c : SeriousCondition_initialize())
#define	Set	(Set_c ? Set_c : Set_initialize())
#define	SetSequence	(SetSequence_c ? SetSequence_c : SetSequence_initialize())
#define	ShortArray	(ShortArray_c ? ShortArray_c : ShortArray_initialize())
#define	ShortInteger	(ShortInteger_c ? ShortInteger_c : ShortInteger_initialize())
#define	SimpleRestart	(SimpleRestart_c ? SimpleRestart_c : SimpleRestart_initialize())
#define	SimpleWarning	(SimpleWarning_c ? SimpleWarning_c : SimpleWarning_initialize())
#define	Socket	(Socket_c ? Socket_c : Socket_initialize())
#define	Stream	(Stream_c ? Stream_c : Stream_initialize())
#define	String	(String_c ? String_c : String_initialize())
#define	StringAssociation	(StringAssociation_c ? StringAssociation_c : StringAssociation_initialize())
#define	StringDictionary	(StringDictionary_c ? StringDictionary_c : StringDictionary_initialize())
#define	Thread	(Thread_c ? Thread_c : Thread_initialize())
#define	Time	(Time_c ? Time_c : Time_initialize())
#define	UnsignedShortArray	(UnsignedShortArray_c ? UnsignedShortArray_c : UnsignedShortArray_initialize())
#define	UnsignedShortInteger	(UnsignedShortInteger_c ? UnsignedShortInteger_c : UnsignedShortInteger_initialize())
#define	Warning	(Warning_c ? Warning_c : Warning_initialize())
#define	WeakPointer	(WeakPointer_c ? WeakPointer_c : WeakPointer_initialize())
#define	XMLNode	(XMLNode_c ? XMLNode_c : XMLNode_initialize())



typedef	object	Abort_t;
typedef	object	Array_t;
typedef	object	Association_t;
typedef	object	BTree_t;
typedef	object	BTreeNode_t;
typedef	object	Behavior_t;
typedef	object	BitArray_t;
typedef	object	BufferedTempFile_t;
typedef	object	Character_t;
typedef	object	CharacterArray_t;
typedef	object	Class_t;
typedef	object	Condition_t;
typedef	object	Constant_t;
typedef	object	Date_t;
typedef	object	DateTime_t;
typedef	object	Dictionary_t;
typedef	object	DoubleFloat_t;
typedef	object	DoubleFloatArray_t;
typedef	object	Dynace_t;
typedef	object	Error_t;
typedef	object	File_t;
typedef	object	FindFile_t;
typedef	object	FloatArray_t;
typedef	object	GenericFunction_t;
typedef	object	IntegerArray_t;
typedef	object	IntegerAssociation_t;
typedef	object	IntegerDictionary_t;
typedef	object	Link_t;
typedef	object	LinkList_t;
typedef	object	LinkObject_t;
typedef	object	LinkObjectSequence_t;
typedef	object	LinkSequence_t;
typedef	object	LinkValue_t;
typedef	object	LongArray_t;
typedef	object	LongInteger_t;
typedef	object	LookupKey_t;
typedef	object	LowFile_t;
typedef	object	Memory_t;
typedef	object	MetaClass_t;
typedef	object	Method_t;
typedef	object	MimeBodyPart_t;
typedef	object	MultipartMime_t;
typedef	object	Number_t;
typedef	object	NumberArray_t;
typedef	object	Object_t;
typedef	object	ObjectArray_t;
typedef	object	ObjectAssociation_t;
typedef	object	ObjectPool_t;
typedef	object	Pipe_t;
typedef	object	Pointer_t;
typedef	object	PointerArray_t;
typedef	object	PropertyList_t;
typedef	object	Restart_t;
typedef	object	Semaphore_t;
typedef	object	Sequence_t;
typedef	object	SeriousCondition_t;
typedef	object	Set_t;
typedef	object	SetSequence_t;
typedef	object	ShortArray_t;
typedef	object	ShortInteger_t;
typedef	object	SimpleRestart_t;
typedef	object	SimpleWarning_t;
typedef	object	Socket_t;
typedef	object	Stream_t;
typedef	object	String_t;
typedef	object	StringAssociation_t;
typedef	object	StringDictionary_t;
typedef	object	Thread_t;
typedef	object	Time_t;
typedef	object	UnsignedShortArray_t;
typedef	object	UnsignedShortInteger_t;
typedef	object	Warning_t;
typedef	object	WeakPointer_t;
typedef	object	XMLNode_t;



extern	object	Generic(gAccept);
extern	object	Generic(gAdd);
extern	object	Generic(gAddAfter);
extern	object	Generic(gAddBTreeNode);
extern	object	Generic(gAddBefore);
extern	object	Generic(gAddBodyPart);
extern	object	Generic(gAddDays);
extern	object	Generic(gAddFirst);
extern	object	Generic(gAddHeader);
extern	object	Generic(gAddHours);
extern	object	Generic(gAddInt);
extern	object	Generic(gAddLast);
extern	object	Generic(gAddMilliseconds);
extern	object	Generic(gAddMinutes);
extern	object	Generic(gAddMonths);
extern	object	Generic(gAddSeconds);
extern	object	Generic(gAddStr);
extern	object	Generic(gAddToPool);
extern	object	Generic(gAddValue);
extern	object	Generic(gAddYears);
extern	object	Generic(gAdvance);
extern	object	Generic(gAlloc);
extern	object	Generic(gAppend);
extern	object	Generic(gAppendChild);
extern	object	Generic(gApplyMask);
extern	object	Generic(gArrayPointer);
extern	object	Generic(gAttributes);
extern	object	Generic(gBasicSize);
extern	object	Generic(gBlockingGetkey);
extern	object	Generic(gBufferSize);
extern	object	Generic(gCalToJul);
extern	object	Generic(gChangeCharAt);
extern	object	Generic(gChangeCharValue);
extern	object	Generic(gChangeDateTimeValues);
extern	object	Generic(gChangeDateValue);
extern	object	Generic(gChangeDoubleValue);
extern	object	Generic(gChangeFunction);
extern	object	Generic(gChangeIntKey);
extern	object	Generic(gChangeKey);
extern	object	Generic(gChangeLongValue);
extern	object	Generic(gChangeNext);
extern	object	Generic(gChangePrevious);
extern	object	Generic(gChangePriority);
extern	object	Generic(gChangeRegisteredMemory);
extern	object	Generic(gChangeShortValue);
extern	object	Generic(gChangeStrValue);
extern	object	Generic(gChangeStringKey);
extern	object	Generic(gChangeTimeValue);
extern	object	Generic(gChangeUShortValue);
extern	object	Generic(gChangeValue);
extern	object	Generic(gChangeValueWithInt);
extern	object	Generic(gChangeValueWithObj);
extern	object	Generic(gChangeValueWithStr);
extern	object	Generic(gCharValue);
extern	object	Generic(gCharValueAt);
extern	object	Generic(gChild);
extern	object	Generic(gCompare);
extern	object	Generic(gCompareI);
extern	object	Generic(gCompareN);
extern	object	Generic(gCompareNI);
extern	object	Generic(gCopy);
extern	object	Generic(gCount);
extern	object	Generic(gCreateAttribute);
extern	object	Generic(gCreateCDATASection);
extern	object	Generic(gCreateComment);
extern	object	Generic(gCreateElement);
extern	object	Generic(gCreateTextNode);
extern	object	Generic(gCurMemUsed);
extern	object	Generic(gDateTimeDifference);
extern	object	Generic(gDateTimeValues);
extern	object	Generic(gDateValue);
extern	object	Generic(gDayName);
extern	object	Generic(gDeepCopy);
extern	object	Generic(gDeepDispose);
extern	object	Generic(gDeepDisposeAllNodes);
extern	object	Generic(gDeepDisposeFirst);
extern	object	Generic(gDeepDisposeGroup);
extern	object	Generic(gDeepDisposeInt);
extern	object	Generic(gDeepDisposeLast);
extern	object	Generic(gDeepDisposeObj);
extern	object	Generic(gDeepDisposeStr);
extern	object	Generic(gDefaultRestart);
extern	object	Generic(gDeleteBTNode);
extern	object	Generic(gDifference);
extern	object	Generic(gDispose);
extern	object	Generic(gDispose1);
extern	object	Generic(gDisposeAllNodes);
extern	object	Generic(gDisposeAllNodes1);
extern	object	Generic(gDisposeAttribute);
extern	object	Generic(gDisposeFirst);
extern	object	Generic(gDisposeGlobalPool);
extern	object	Generic(gDisposeGroup);
extern	object	Generic(gDisposeInt);
extern	object	Generic(gDisposeItem);
extern	object	Generic(gDisposeLast);
extern	object	Generic(gDisposeObj);
extern	object	Generic(gDisposeObject);
extern	object	Generic(gDisposePropertyList);
extern	object	Generic(gDisposeStr);
extern	object	Generic(gDoesNotImplement);
extern	object	Generic(gDontCollect);
extern	object	Generic(gDoubleValue);
extern	object	Generic(gDrop);
extern	object	Generic(gDumpMemoryDiff);
extern	object	Generic(gDumpObjects);
extern	object	Generic(gDumpObjectsDiff);
extern	object	Generic(gDumpObjectsString);
extern	object	Generic(gDumpXML);
extern	object	Generic(gEndOfStream);
extern	object	Generic(gEnterCriticalSection);
extern	object	Generic(gEqual);
extern	object	Generic(gError);
extern	object	Generic(gFileHandle);
extern	object	Generic(gFind);
extern	object	Generic(gFindAdd);
extern	object	Generic(gFindAddInt);
extern	object	Generic(gFindAddStr);
extern	object	Generic(gFindAddValue);
extern	object	Generic(gFindBTNEQ);
extern	object	Generic(gFindBTNFirst);
extern	object	Generic(gFindBTNGE);
extern	object	Generic(gFindBTNGT);
extern	object	Generic(gFindBTNLE);
extern	object	Generic(gFindBTNLT);
extern	object	Generic(gFindBTNLast);
extern	object	Generic(gFindChildNode);
extern	object	Generic(gFindChildNodeWithText);
extern	object	Generic(gFindClass);
extern	object	Generic(gFindEQ);
extern	object	Generic(gFindFirst);
extern	object	Generic(gFindGE);
extern	object	Generic(gFindGT);
extern	object	Generic(gFindGeneric);
extern	object	Generic(gFindInt);
extern	object	Generic(gFindLE);
extern	object	Generic(gFindLT);
extern	object	Generic(gFindLast);
extern	object	Generic(gFindMethod);
extern	object	Generic(gFindMethodObject);
extern	object	Generic(gFindNext);
extern	object	Generic(gFindNextNode);
extern	object	Generic(gFindNode);
extern	object	Generic(gFindPrev);
extern	object	Generic(gFindStr);
extern	object	Generic(gFindValue);
extern	object	Generic(gFindValueInt);
extern	object	Generic(gFindValueStr);
extern	object	Generic(gFirst);
extern	object	Generic(gFirstAttribute);
extern	object	Generic(gFixInvalidDate);
extern	object	Generic(gFlush);
extern	object	Generic(gForAll);
extern	object	Generic(gFormatChar);
extern	object	Generic(gFormatDate);
extern	object	Generic(gFormatDateTime);
extern	object	Generic(gFormatNumber);
extern	object	Generic(gFormatTime);
extern	object	Generic(gFunction);
extern	object	Generic(gGC);
extern	object	Generic(gGCDispose);
extern	object	Generic(gGetAll);
extern	object	Generic(gGetAttribute);
extern	object	Generic(gGetAttributeValue);
extern	object	Generic(gGetBodyContent);
extern	object	Generic(gGetBodyParts);
extern	object	Generic(gGetBoundaryString);
extern	object	Generic(gGetCharFromNode);
extern	object	Generic(gGetCipher);
extern	object	Generic(gGetContentType);
extern	object	Generic(gGetErrorCode);
extern	object	Generic(gGetErrorStr);
extern	object	Generic(gGetFloatFromNode);
extern	object	Generic(gGetGenericPtr);
extern	object	Generic(gGetHeader);
extern	object	Generic(gGetHeaders);
extern	object	Generic(gGetIntFromNode);
extern	object	Generic(gGetName);
extern	object	Generic(gGetParent);
extern	object	Generic(gGetPeerCertificateIssuerName);
extern	object	Generic(gGetPeerCertificateSubjectName);
extern	object	Generic(gGetSessionInfo);
extern	object	Generic(gGetStr);
extern	object	Generic(gGetTotalBytesRead);
extern	object	Generic(gGets);
extern	object	Generic(gGroupRemove);
extern	object	Generic(gHash);
extern	object	Generic(gHold);
extern	object	Generic(gHours);
extern	object	Generic(gHowManyBitsOfPeerPublicKey);
extern	object	Generic(gIPAddress);
extern	object	Generic(gIPAddressStr);
extern	object	Generic(gIncNelm);
extern	object	Generic(gIndex);
extern	object	Generic(gIndexOrigin);
extern	object	Generic(gInit);
extern	object	Generic(gInitLink);
extern	object	Generic(gInsertBefore);
extern	object	Generic(gInsertObjAt);
extern	object	Generic(gInstanceSize);
extern	object	Generic(gIntKey);
extern	object	Generic(gIntValue);
extern	object	Generic(gInvalidObject);
extern	object	Generic(gInvalidType);
extern	object	Generic(gIota);
extern	object	Generic(gIsKindOf);
extern	object	Generic(gJulToCal);
extern	object	Generic(gJulian);
extern	object	Generic(gJustifyCenter);
extern	object	Generic(gJustifyLeft);
extern	object	Generic(gJustifyRight);
extern	object	Generic(gKey);
extern	object	Generic(gKill);
extern	object	Generic(gLast);
extern	object	Generic(gLeaveCriticalSection);
extern	object	Generic(gLength);
extern	object	Generic(gList);
extern	object	Generic(gLoadJavaClass);
extern	object	Generic(gLoadMask);
extern	object	Generic(gLock);
extern	object	Generic(gLongValue);
extern	object	Generic(gLookup);
extern	object	Generic(gMakeServer);
extern	object	Generic(gMarkMemoryBeginning);
extern	object	Generic(gMarkObject);
extern	object	Generic(gMarkRange);
extern	object	Generic(gMarkingMethod);
extern	object	Generic(gMaskFunction);
extern	object	Generic(gMaxAfterGC);
extern	object	Generic(gMaxMemUsed);
extern	object	Generic(gMilliseconds);
extern	object	Generic(gMinutes);
extern	object	Generic(gMode);
extern	object	Generic(gMonthName);
extern	object	Generic(gMoreHandles);
extern	object	Generic(gMoveAfter);
extern	object	Generic(gMoveBefore);
extern	object	Generic(gMoveBeginning);
extern	object	Generic(gMoveEnd);
extern	object	Generic(gName);
extern	object	Generic(gNew);
extern	object	Generic(gNewArray);
extern	object	Generic(gNewClass);
extern	object	Generic(gNewDateTime);
extern	object	Generic(gNewDocument);
extern	object	Generic(gNewFindFile);
extern	object	Generic(gNewGeneric);
extern	object	Generic(gNewGlobalPool);
extern	object	Generic(gNewGlobalPoolWithSize);
extern	object	Generic(gNewMethod);
extern	object	Generic(gNewMimeBodyPart);
extern	object	Generic(gNewMultipartMime);
extern	object	Generic(gNewNode);
extern	object	Generic(gNewSemaphore);
extern	object	Generic(gNewSetSeq);
extern	object	Generic(gNewStdClass);
extern	object	Generic(gNewThread);
extern	object	Generic(gNewWithChar);
extern	object	Generic(gNewWithDouble);
extern	object	Generic(gNewWithInt);
extern	object	Generic(gNewWithIntObj);
extern	object	Generic(gNewWithLong);
extern	object	Generic(gNewWithObj);
extern	object	Generic(gNewWithObjObj);
extern	object	Generic(gNewWithPtr);
extern	object	Generic(gNewWithStr);
extern	object	Generic(gNewWithStrInt);
extern	object	Generic(gNewWithStrObj);
extern	object	Generic(gNewWithStream);
extern	object	Generic(gNewWithUnsigned);
extern	object	Generic(gNext);
extern	object	Generic(gNextFile);
extern	object	Generic(gNow);
extern	object	Generic(gNth);
extern	object	Generic(gNumbGC);
extern	object	Generic(gNumbPieces);
extern	object	Generic(gObjectChecking);
extern	object	Generic(gObjectSerialNumber);
extern	object	Generic(gOpenFile);
extern	object	Generic(gOpenLowFile);
extern	object	Generic(gOpenTempFile);
extern	object	Generic(gParent);
extern	object	Generic(gParseFile);
extern	object	Generic(gParseMultipartFromString);
extern	object	Generic(gParseString);
extern	object	Generic(gPiece);
extern	object	Generic(gPointerValue);
extern	object	Generic(gPop);
extern	object	Generic(gPopulateStringFromNode);
extern	object	Generic(gPosition);
extern	object	Generic(gPrevious);
extern	object	Generic(gPrint);
extern	object	Generic(gPrintLength);
extern	object	Generic(gPrintValue);
extern	object	Generic(gPriority);
extern	object	Generic(gProcess);
extern	object	Generic(gPropertyGet);
extern	object	Generic(gPropertyPut);
extern	object	Generic(gPropertyRemove);
extern	object	Generic(gPropertySetAutoDispose);
extern	object	Generic(gProxyConnect);
extern	object	Generic(gPush);
extern	object	Generic(gPutc);
extern	object	Generic(gPuts);
extern	object	Generic(gRank);
extern	object	Generic(gRead);
extern	object	Generic(gReadInt32);
extern	object	Generic(gRecvFile);
extern	object	Generic(gRegisterMemory);
extern	object	Generic(gRelease);
extern	object	Generic(gReleaseSemaphore);
extern	object	Generic(gRemove);
extern	object	Generic(gRemoveAttribute);
extern	object	Generic(gRemoveFirst);
extern	object	Generic(gRemoveFromPool);
extern	object	Generic(gRemoveInt);
extern	object	Generic(gRemoveLast);
extern	object	Generic(gRemoveMask);
extern	object	Generic(gRemoveNode);
extern	object	Generic(gRemoveObj);
extern	object	Generic(gRemoveRegisteredMemory);
extern	object	Generic(gRemoveStr);
extern	object	Generic(gRemoveWaits);
extern	object	Generic(gResize);
extern	object	Generic(gResizeMethodCache);
extern	object	Generic(gRetreat);
extern	object	Generic(gRoom);
extern	object	Generic(gRound);
extern	object	Generic(gSaveXML);
extern	object	Generic(gSeconds);
extern	object	Generic(gSeek);
extern	object	Generic(gSendFile);
extern	object	Generic(gSendStr);
extern	object	Generic(gSequence);
extern	object	Generic(gSequenceLinks);
extern	object	Generic(gServerSocketConnect);
extern	object	Generic(gSetAttribute);
extern	object	Generic(gSetErrorFunction);
extern	object	Generic(gSetFunction);
extern	object	Generic(gSetMaskFiller);
extern	object	Generic(gSetMemoryBufferArea);
extern	object	Generic(gSetMoreHandles);
extern	object	Generic(gSetNodeName);
extern	object	Generic(gSetNodeValue);
extern	object	Generic(gSetPropertyList);
extern	object	Generic(gSetTempSubDir);
extern	object	Generic(gSetTopNode);
extern	object	Generic(gShape);
extern	object	Generic(gShortValue);
extern	object	Generic(gShouldNotImplement);
extern	object	Generic(gSignal);
extern	object	Generic(gSize);
extern	object	Generic(gSocketConnect);
extern	object	Generic(gStackAlloc);
extern	object	Generic(gState);
extern	object	Generic(gStringKey);
extern	object	Generic(gStringRep);
extern	object	Generic(gStringRepValue);
extern	object	Generic(gStringToXML);
extern	object	Generic(gStringValue);
extern	object	Generic(gStripCenter);
extern	object	Generic(gStripLeft);
extern	object	Generic(gStripRight);
extern	object	Generic(gSubClasses);
extern	object	Generic(gSubString);
extern	object	Generic(gSubclassResponsibility);
extern	object	Generic(gSuperClasses);
extern	object	Generic(gTake);
extern	object	Generic(gTimeDifference);
extern	object	Generic(gTimeStringRepValue);
extern	object	Generic(gTimeValue);
extern	object	Generic(gTimedRead);
extern	object	Generic(gTimedReadMS);
extern	object	Generic(gTimedWrite);
extern	object	Generic(gToLower);
extern	object	Generic(gToUpper);
extern	object	Generic(gToday);
extern	object	Generic(gTrace);
extern	object	Generic(gTracePrint);
extern	object	Generic(gTruncate);
extern	object	Generic(gType);
extern	object	Generic(gUnLock);
extern	object	Generic(gUnsignedShortValue);
extern	object	Generic(gUpdateLength);
extern	object	Generic(gValidDate);
extern	object	Generic(gValidDateTime);
extern	object	Generic(gValidTime);
extern	object	Generic(gValue);
extern	object	Generic(gWaitFor);
extern	object	Generic(gWaitSemaphore);
extern	object	Generic(gWrite);
extern	object	Generic(gWriteInt32);
extern	object	Generic(gWriteTime);
extern	object	Generic(gXMLToString);
extern	object	Generic(gXPath);
extern	object	Generic(vBitValue);
extern	object	Generic(vBuild);
extern	object	Generic(vChangeBitValue);
extern	object	Generic(vChangeCharValue);
extern	object	Generic(vChangeDoubleValue);
extern	object	Generic(vChangeLongValue);
extern	object	Generic(vChangeShortValue);
extern	object	Generic(vChangeUShortValue);
extern	object	Generic(vChangeValue);
extern	object	Generic(vCharValue);
extern	object	Generic(vDoubleValue);
extern	object	Generic(vError);
extern	object	Generic(vGetValues);
extern	object	Generic(vLongValue);
extern	object	Generic(vMakeList);
extern	object	Generic(vNew);
extern	object	Generic(vPointerValue);
extern	object	Generic(vPrintf);
extern	object	Generic(vReshape);
extern	object	Generic(vShortValue);
extern	object	Generic(vSprintf);
extern	object	Generic(vUnsignedShortValue);
extern	object	Generic(vValue);


#undef	START_PROTOTYPES

typedef	objrtn	(*gAccept_t)(object self);
typedef	objrtn	(*gAdd_t)(object self, object luk);
typedef	objrtn	(*gAddAfter_t)(object self, object lnk);
typedef	objrtn	(*gAddBTreeNode_t)(object self, ifun cfun, object key, object data, int replace, int *replaced, object prev, object *old);
typedef	objrtn	(*gAddBefore_t)(object self, object lnk);
typedef	objrtn	(*gAddBodyPart_t)(object self, object bodyPart);
typedef	objrtn	(*gAddDays_t)(object self, long days);
typedef	objrtn	(*gAddFirst_t)(object self, object lnk);
typedef	objrtn	(*gAddHeader_t)(object self, char *name, char *value);
typedef	objrtn	(*gAddHours_t)(object self, long h);
typedef	objrtn	(*gAddInt_t)(object self, int key, object value);
typedef	objrtn	(*gAddLast_t)(object self, object lnk);
typedef	objrtn	(*gAddMilliseconds_t)(object self, long l);
typedef	objrtn	(*gAddMinutes_t)(object self, long m);
typedef	objrtn	(*gAddMonths_t)(object self, int months);
typedef	objrtn	(*gAddSeconds_t)(object self, long s);
typedef	objrtn	(*gAddStr_t)(object self, char *key, object value);
typedef	objrtn	(*gAddToPool_t)(object self, int deepFlag, object obj);
typedef	objrtn	(*gAddValue_t)(object self, object key, object value);
typedef	objrtn	(*gAddYears_t)(object self, int years);
typedef	long	(*gAdvance_t)(object self, long n);
typedef	objrtn	(*gAlloc_t)(object self);
typedef	objrtn	(*gAppend_t)(object self, object obj);
typedef	objrtn	(*gAppendChild_t)(object self, object node);
typedef	objrtn	(*gApplyMask_t)(object self, char *inmask, char *intext);
typedef	void *	(*gArrayPointer_t)(object self);
typedef	unsigned	(*gAttributes_t)(object self);
typedef	int	(*gBasicSize_t)(object self);
typedef	int	(*gBlockingGetkey_t)(object self);
typedef	int	(*gBufferSize_t)(object self);
typedef	long	(*gCalToJul_t)(object self, long dt);
typedef	objrtn	(*gChangeCharAt_t)(object self, int i, int c);
typedef	objrtn	(*gChangeCharValue_t)(object self, int val);
typedef	objrtn	(*gChangeDateTimeValues_t)(object self, long dt, long tm);
typedef	objrtn	(*gChangeDateValue_t)(object self, long dt);
typedef	objrtn	(*gChangeDoubleValue_t)(object self, double val);
typedef	ofun	(*gChangeFunction_t)(object self, ofun fun);
typedef	objrtn	(*gChangeIntKey_t)(object self, int key);
typedef	objrtn	(*gChangeKey_t)(object self, object key);
typedef	objrtn	(*gChangeLongValue_t)(object self, long val);
typedef	objrtn	(*gChangeNext_t)(object self, object next);
typedef	objrtn	(*gChangePrevious_t)(object self, object prev);
typedef	objrtn	(*gChangePriority_t)(object self, int p);
typedef	void *	(*gChangeRegisteredMemory_t)(object self, void *pp, void *beg, long size);
typedef	objrtn	(*gChangeShortValue_t)(object self, int val);
typedef	objrtn	(*gChangeStrValue_t)(object self, char *str);
typedef	objrtn	(*gChangeStringKey_t)(object self, char *key);
typedef	objrtn	(*gChangeTimeValue_t)(object self, long val);
typedef	objrtn	(*gChangeUShortValue_t)(object self, unsigned val);
typedef	objrtn	(*gChangeValue_t)(object self, object value);
typedef	objrtn	(*gChangeValueWithInt_t)(object self, int key, object val);
typedef	objrtn	(*gChangeValueWithObj_t)(object self, object key, object val);
typedef	objrtn	(*gChangeValueWithStr_t)(object self, char *key, object val);
typedef	char	(*gCharValue_t)(object self);
typedef	char	(*gCharValueAt_t)(object self, int i);
typedef	objrtn	(*gChild_t)(object self);
typedef	int	(*gCompare_t)(object self, object obj2);
typedef	int	(*gCompareI_t)(object self, object obj);
typedef	int	(*gCompareN_t)(object self, object obj, int n);
typedef	int	(*gCompareNI_t)(object self, object obj, int n);
typedef	objrtn	(*gCopy_t)(object self);
typedef	int	(*gCount_t)(object self);
typedef	objrtn	(*gCreateAttribute_t)(object self, char *name, char *value);
typedef	objrtn	(*gCreateCDATASection_t)(object self, char *text);
typedef	objrtn	(*gCreateComment_t)(object self, char *text);
typedef	objrtn	(*gCreateElement_t)(object self, char *name);
typedef	objrtn	(*gCreateTextNode_t)(object self, char *text);
typedef	long	(*gCurMemUsed_t)(object self);
typedef	objrtn	(*gDateTimeDifference_t)(object self, object dt, long *ddr, long *tdr);
typedef	objrtn	(*gDateTimeValues_t)(object self, long *dt, long *tm);
typedef	long	(*gDateValue_t)(object self);
typedef	objrtn	(*gDayName_t)(object self);
typedef	objrtn	(*gDeepCopy_t)(object self);
typedef	objrtn	(*gDeepDispose_t)(object self);
typedef	objrtn	(*gDeepDisposeAllNodes_t)(object self);
typedef	objrtn	(*gDeepDisposeFirst_t)(object self);
typedef	objrtn	(*gDeepDisposeGroup_t)(object self, int (*fun)());
typedef	objrtn	(*gDeepDisposeInt_t)(object self, int key);
typedef	objrtn	(*gDeepDisposeLast_t)(object self);
typedef	objrtn	(*gDeepDisposeObj_t)(object self, object luk);
typedef	objrtn	(*gDeepDisposeStr_t)(object self, char *key);
typedef	objrtn	(*gDefaultRestart_t)(object self);
typedef	objrtn	(*gDeleteBTNode_t)(object self, ifun cfun, object key, int deep, object prev);
typedef	long	(*gDifference_t)(object self, object dt);
typedef	objrtn	(*gDispose_t)(object self);
typedef	objrtn	(*gDispose1_t)(object self);
typedef	objrtn	(*gDisposeAllNodes_t)(object self);
typedef	objrtn	(*gDisposeAllNodes1_t)(object self);
typedef	objrtn	(*gDisposeAttribute_t)(object self, char *name);
typedef	objrtn	(*gDisposeFirst_t)(object self);
typedef	objrtn	(*gDisposeGlobalPool_t)(object self);
typedef	objrtn	(*gDisposeGroup_t)(object self, int (*fun)());
typedef	objrtn	(*gDisposeInt_t)(object self, int key);
typedef	objrtn	(*gDisposeItem_t)(object self);
typedef	objrtn	(*gDisposeLast_t)(object self);
typedef	objrtn	(*gDisposeObj_t)(object self, object luk);
typedef	objrtn	(*gDisposeObject_t)(object self, object obj);
typedef	objrtn	(*gDisposePropertyList_t)(object self);
typedef	objrtn	(*gDisposeStr_t)(object self, char *key);
typedef	void	(*gDoesNotImplement_t)(object self, object gen);
typedef	objrtn	(*gDontCollect_t)(object self);
typedef	double	(*gDoubleValue_t)(object self);
typedef	objrtn	(*gDrop_t)(object self, int n);
typedef	objrtn	(*gDumpMemoryDiff_t)(object self, object d1, char *fname);
typedef	objrtn	(*gDumpObjects_t)(object self, char *file, int type);
typedef	objrtn	(*gDumpObjectsDiff_t)(object self, object sd1, object sd2);
typedef	objrtn	(*gDumpObjectsString_t)(object self, int type);
typedef	objrtn	(*gDumpXML_t)(object self, int level, object stm, int next);
typedef	int	(*gEndOfStream_t)(object self);
typedef	objrtn	(*gEnterCriticalSection_t)(object self);
typedef	int	(*gEqual_t)(object self, object obj2);
typedef	objrtn	(*gError_t)(object self, char *msg);
typedef	int	(*gFileHandle_t)(object self);
typedef	objrtn	(*gFind_t)(object self, object luk);
typedef	objrtn	(*gFindAdd_t)(object self, object luk);
typedef	objrtn	(*gFindAddInt_t)(object self, int key, object value);
typedef	objrtn	(*gFindAddStr_t)(object self, char *key, object value);
typedef	objrtn	(*gFindAddValue_t)(object self, object key, object value);
typedef	objrtn	(*gFindBTNEQ_t)(object self, ifun cfun, object key, object *foundKey);
typedef	objrtn	(*gFindBTNFirst_t)(object self, ifun cfun, object *foundKey);
typedef	objrtn	(*gFindBTNGE_t)(object self, ifun cfun, object key, object *foundKey);
typedef	objrtn	(*gFindBTNGT_t)(object self, ifun cfun, object key, object *foundKey);
typedef	objrtn	(*gFindBTNLE_t)(object self, ifun cfun, object key, object *foundKey);
typedef	objrtn	(*gFindBTNLT_t)(object self, ifun cfun, object key, object *foundKey);
typedef	objrtn	(*gFindBTNLast_t)(object self, ifun cfun, object *foundKey);
typedef	objrtn	(*gFindChildNode_t)(object self, char *name);
typedef	objrtn	(*gFindChildNodeWithText_t)(object self, char *name, char *txt);
typedef	objrtn	(*gFindClass_t)(object self, char *name);
typedef	objrtn	(*gFindEQ_t)(object self, object key, object *foundKey);
typedef	objrtn	(*gFindFirst_t)(object self, object *foundKey);
typedef	objrtn	(*gFindGE_t)(object self, object key, object *foundKey);
typedef	objrtn	(*gFindGT_t)(object self, object key, object *foundKey);
typedef	objrtn	(*gFindGeneric_t)(object self, char *nam);
typedef	objrtn	(*gFindInt_t)(object self, int key);
typedef	objrtn	(*gFindLE_t)(object self, object key, object *foundKey);
typedef	objrtn	(*gFindLT_t)(object self, object key, object *foundKey);
typedef	objrtn	(*gFindLast_t)(object self, object *foundKey);
typedef	ofun	(*gFindMethod_t)(object self, object generic, int lev);
typedef	objrtn	(*gFindMethodObject_t)(object self, object generic, int lev);
typedef	objrtn	(*gFindNext_t)(object self, object *foundKey);
typedef	objrtn	(*gFindNextNode_t)(object self, char *name);
typedef	objrtn	(*gFindNode_t)(object self, char *name);
typedef	objrtn	(*gFindPrev_t)(object self, object *foundKey);
typedef	objrtn	(*gFindStr_t)(object self, char *key);
typedef	objrtn	(*gFindValue_t)(object self, object key);
typedef	objrtn	(*gFindValueInt_t)(object self, int key);
typedef	objrtn	(*gFindValueStr_t)(object self, char *key);
typedef	objrtn	(*gFirst_t)(object self);
typedef	objrtn	(*gFirstAttribute_t)(object self);
typedef	int	(*gFixInvalidDate_t)(object self, int mode);
typedef	int	(*gFlush_t)(object self);
typedef	objrtn	(*gForAll_t)(object self, object (*fun)());
typedef	objrtn	(*gFormatChar_t)(object self);
typedef	objrtn	(*gFormatDate_t)(object self, char *msk);
typedef	objrtn	(*gFormatDateTime_t)(object self, char *dtbuf, char *tmbuf);
typedef	objrtn	(*gFormatNumber_t)(object self, char *msk, int wth, int dp);
typedef	objrtn	(*gFormatTime_t)(object self, char *msk);
typedef	ofun	(*gFunction_t)(object self);
typedef	objrtn	(*gGC_t)(object self);
typedef	objrtn	(*gGCDispose_t)(object self);
typedef	objrtn	(*gGetAll_t)(object self);
typedef	objrtn	(*gGetAttribute_t)(object self, char *name);
typedef	char *	(*gGetAttributeValue_t)(object self, char *name);
typedef	char *	(*gGetBodyContent_t)(object self);
typedef	objrtn	(*gGetBodyParts_t)(object self);
typedef	char *	(*gGetBoundaryString_t)(object self);
typedef	char	(*gGetCharFromNode_t)(object self, char *node);
typedef	char *	(*gGetCipher_t)(object self);
typedef	char *	(*gGetContentType_t)(object self);
typedef	int	(*gGetErrorCode_t)(object self);
typedef	char *	(*gGetErrorStr_t)(object self);
typedef	float	(*gGetFloatFromNode_t)(object self, char *node);
typedef	void *	(*gGetGenericPtr_t)(object self);
typedef	char *	(*gGetHeader_t)(object self, char *name);
typedef	objrtn	(*gGetHeaders_t)(object self);
typedef	int	(*gGetIntFromNode_t)(object self, char *node);
typedef	char *	(*gGetName_t)(object self);
typedef	objrtn	(*gGetParent_t)(object self);
typedef	char *	(*gGetPeerCertificateIssuerName_t)(object self);
typedef	char *	(*gGetPeerCertificateSubjectName_t)(object self);
typedef	objrtn	(*gGetSessionInfo_t)(object self, char **session1, char **session2, char **session3);
typedef	int	(*gGetStr_t)(object self, char *str);
typedef	long	(*gGetTotalBytesRead_t)(object self);
typedef	char *	(*gGets_t)(object self, char *buf, int n);
typedef	objrtn	(*gGroupRemove_t)(object self, int (*fun)());
typedef	int	(*gHash_t)(object self);
typedef	objrtn	(*gHold_t)(object self);
typedef	int	(*gHours_t)(object self);
typedef	int	(*gHowManyBitsOfPeerPublicKey_t)(object self);
typedef	unsigned long	(*gIPAddress_t)(object self);
typedef	char *	(*gIPAddressStr_t)(object self, char *buf);
typedef	objrtn	(*gIncNelm_t)(object self, int inc);
typedef	void *	(*gIndex_t)(object self, va_list _rest_);
typedef	objrtn	(*gIndexOrigin_t)(object self, int n);
typedef	objrtn	(*gInit_t)(object self);
typedef	objrtn	(*gInitLink_t)(object self, object list, object prev, object next);
typedef	objrtn	(*gInsertBefore_t)(object self, object node);
typedef	objrtn	(*gInsertObjAt_t)(object self, object lnk, int idx);
typedef	int	(*gInstanceSize_t)(object self);
typedef	int	(*gIntKey_t)(object self);
typedef	int	(*gIntValue_t)(object self);
typedef	void	(*gInvalidObject_t)(object self, int argn, object arg1);
typedef	void	(*gInvalidType_t)(object self, int argn, object arg1, object cls, object arg);
typedef	objrtn	(*gIota_t)(object self, int n);
typedef	int	(*gIsKindOf_t)(object self, object aCls);
typedef	long	(*gJulToCal_t)(object self, long dt);
typedef	long	(*gJulian_t)(object self);
typedef	objrtn	(*gJustifyCenter_t)(object self);
typedef	objrtn	(*gJustifyLeft_t)(object self);
typedef	objrtn	(*gJustifyRight_t)(object self);
typedef	objrtn	(*gKey_t)(object self);
typedef	objrtn	(*gKill_t)(object self, int rtn);
typedef	objrtn	(*gLast_t)(object self);
typedef	objrtn	(*gLeaveCriticalSection_t)(object self);
typedef	long	(*gLength_t)(object self);
typedef	objrtn	(*gList_t)(object self);
typedef	objrtn	(*gLoadJavaClass_t)(object self, char *name);
typedef	char *	(*gLoadMask_t)(object self, char *inmask);
typedef	int	(*gLock_t)(object self, unsigned long start, unsigned long len, int wait);
typedef	long	(*gLongValue_t)(object self);
typedef	objrtn	(*gLookup_t)(object self, object luk, int mode, int deep, int type, object value);
typedef	objrtn	(*gMakeServer_t)(object self, int port, int ssl);
typedef	objrtn	(*gMarkMemoryBeginning_t)(object self);
typedef	void	(*gMarkObject_t)(object self, object obj);
typedef	void	(*gMarkRange_t)(object self, char _HUGE_ **from, char _HUGE_ **to);
typedef	objrtn	(*gMarkingMethod_t)(object self, ofun mf);
typedef	ifun	(*gMaskFunction_t)(object self, char ch);
typedef	long	(*gMaxAfterGC_t)(object self);
typedef	long	(*gMaxMemUsed_t)(object self);
typedef	int	(*gMilliseconds_t)(object self);
typedef	int	(*gMinutes_t)(object self);
typedef	objrtn	(*gMode_t)(object self, int rblock, int wblock);
typedef	objrtn	(*gMonthName_t)(object self);
typedef	objrtn	(*gMoreHandles_t)(object self);
typedef	objrtn	(*gMoveAfter_t)(object self, object lnk);
typedef	objrtn	(*gMoveBefore_t)(object self, object lnk);
typedef	objrtn	(*gMoveBeginning_t)(object self);
typedef	objrtn	(*gMoveEnd_t)(object self);
typedef	char *	(*gName_t)(object self);
typedef	objrtn	(*gNew_t)(object self);
typedef	objrtn	(*gNewArray_t)(object self, int type, int rank, va_list _rest_);
typedef	objrtn	(*gNewClass_t)(object self, char *name, int ivsize, int cvsize, object superclasses, ...);
typedef	objrtn	(*gNewDateTime_t)(object self, long dt, long tm);
typedef	objrtn	(*gNewDocument_t)(object self);
typedef	objrtn	(*gNewFindFile_t)(object self, char *name, int attr);
typedef	objrtn	(*gNewGeneric_t)(object self, char *n, void *fp);
typedef	objrtn	(*gNewGlobalPool_t)(object self);
typedef	objrtn	(*gNewGlobalPoolWithSize_t)(object self, int siz);
typedef	objrtn	(*gNewMethod_t)(object self, char *n, object c, object gen, ofun methf, ofun methf2);
typedef	objrtn	(*gNewMimeBodyPart_t)(object self, char *content);
typedef	objrtn	(*gNewMultipartMime_t)(object self, char *subType, char *boundaryString);
typedef	objrtn	(*gNewNode_t)(object self, object btree, int type);
typedef	objrtn	(*gNewSemaphore_t)(object self, char *name, int cnt, int mx);
typedef	objrtn	(*gNewSetSeq_t)(object self, int size, int nelm, void *tab);
typedef	objrtn	(*gNewStdClass_t)(object self, char *name, int ivsize, object mc, int nipib, object superclasses, ...);
typedef	objrtn	(*gNewThread_t)(object self, char *name, ifun fun, int priority, void *arg, int run, int autoDispose);
typedef	objrtn	(*gNewWithChar_t)(object self, int val);
typedef	objrtn	(*gNewWithDouble_t)(object self, double val);
typedef	objrtn	(*gNewWithInt_t)(object self, int val);
typedef	objrtn	(*gNewWithIntObj_t)(object self, int key, object value);
typedef	objrtn	(*gNewWithLong_t)(object self, long val);
typedef	objrtn	(*gNewWithObj_t)(object self, object value);
typedef	objrtn	(*gNewWithObjObj_t)(object self, object key, object val);
typedef	objrtn	(*gNewWithPtr_t)(object self, void *val);
typedef	objrtn	(*gNewWithStr_t)(object self, char *so);
typedef	objrtn	(*gNewWithStrInt_t)(object self, char *name, int bufsiz);
typedef	objrtn	(*gNewWithStrObj_t)(object self, char *key, object val);
typedef	objrtn	(*gNewWithStream_t)(object self, char *name, FILE *fp);
typedef	objrtn	(*gNewWithUnsigned_t)(object self, unsigned val);
typedef	objrtn	(*gNext_t)(object self);
typedef	char *	(*gNextFile_t)(object self);
typedef	objrtn	(*gNow_t)(object self);
typedef	objrtn	(*gNth_t)(object self, int idx);
typedef	long	(*gNumbGC_t)(object self);
typedef	int	(*gNumbPieces_t)(object self, char d);
typedef	objrtn	(*gObjectChecking_t)(object self, int x);
typedef	unsigned long	(*gObjectSerialNumber_t)(object self);
typedef	objrtn	(*gOpenFile_t)(object self, char *name, char *mode);
typedef	objrtn	(*gOpenLowFile_t)(object self, char *name, int oflag, int pmode);
typedef	objrtn	(*gOpenTempFile_t)(object self);
typedef	objrtn	(*gParent_t)(object self);
typedef	objrtn	(*gParseFile_t)(object self, char *file, long *line, long *col, long *pos);
typedef	objrtn	(*gParseMultipartFromString_t)(object self, char *content, char *boundary);
typedef	objrtn	(*gParseString_t)(object self, char *str, long *line, long *col, long *pos);
typedef	objrtn	(*gPiece_t)(object self, char d, int n);
typedef	void *	(*gPointerValue_t)(object self);
typedef	objrtn	(*gPop_t)(object self);
typedef	objrtn	(*gPopulateStringFromNode_t)(object self, char *to, char *node);
typedef	long	(*gPosition_t)(object self);
typedef	objrtn	(*gPrevious_t)(object self);
typedef	objrtn	(*gPrint_t)(object self, object stream);
typedef	int	(*gPrintLength_t)(object self, int t);
typedef	objrtn	(*gPrintValue_t)(object self, object stream);
typedef	int	(*gPriority_t)(object self);
typedef	objrtn	(*gProcess_t)(object self);
typedef	objrtn	(*gPropertyGet_t)(object self, char *prop);
typedef	objrtn	(*gPropertyPut_t)(object self, char *prop, int autoDispose, object val);
typedef	objrtn	(*gPropertyRemove_t)(object self, char *prop);
typedef	objrtn	(*gPropertySetAutoDispose_t)(object self, char *prop, int autoDispose);
typedef	objrtn	(*gProxyConnect_t)(object self, char *addr, int port, short int flag, char *proxy_addr, int proxy_port, char *proxy_user, char *proxy_pw);
typedef	objrtn	(*gPush_t)(object self, object obj);
typedef	int	(*gPutc_t)(object self, int i);
typedef	int	(*gPuts_t)(object self, char *str);
typedef	unsigned	(*gRank_t)(object self);
typedef	int	(*gRead_t)(object self, char *buf, unsigned n);
typedef	int	(*gReadInt32_t)(object self, int *val);
typedef	int	(*gRecvFile_t)(object self, char *toFile);
typedef	void *	(*gRegisterMemory_t)(object self, void *beg, long size);
typedef	objrtn	(*gRelease_t)(object self, int yld);
typedef	objrtn	(*gReleaseSemaphore_t)(object self);
typedef	objrtn	(*gRemove_t)(object self);
typedef	objrtn	(*gRemoveAttribute_t)(object self, char *name);
typedef	objrtn	(*gRemoveFirst_t)(object self);
typedef	objrtn	(*gRemoveFromPool_t)(object self, object obj);
typedef	objrtn	(*gRemoveInt_t)(object self, int key);
typedef	objrtn	(*gRemoveLast_t)(object self);
typedef	objrtn	(*gRemoveMask_t)(object self, char *inmask, char *text);
typedef	objrtn	(*gRemoveNode_t)(object self);
typedef	objrtn	(*gRemoveObj_t)(object self, object luk);
typedef	void	(*gRemoveRegisteredMemory_t)(object self, void *pp);
typedef	objrtn	(*gRemoveStr_t)(object self, char *key);
typedef	objrtn	(*gRemoveWaits_t)(object self, object thrd);
typedef	objrtn	(*gResize_t)(object self, int size);
typedef	objrtn	(*gResizeMethodCache_t)(object self, int classes, int generics);
typedef	long	(*gRetreat_t)(object self, long n);
typedef	int	(*gRoom_t)(object self);
typedef	objrtn	(*gRound_t)(object self, int p);
typedef	int	(*gSaveXML_t)(object self, char *file);
typedef	int	(*gSeconds_t)(object self);
typedef	long	(*gSeek_t)(object self, long n);
typedef	int	(*gSendFile_t)(object self, char *fromFile, char *toFile);
typedef	int	(*gSendStr_t)(object self, char *str);
typedef	objrtn	(*gSequence_t)(object self);
typedef	objrtn	(*gSequenceLinks_t)(object self);
typedef	objrtn	(*gServerSocketConnect_t)(object self);
typedef	objrtn	(*gSetAttribute_t)(object self, char *name, char *value);
typedef	ifun	(*gSetErrorFunction_t)(object self, ifun fun);
typedef	ofun	(*gSetFunction_t)(object self, int (*fun)());
typedef	char	(*gSetMaskFiller_t)(object self, char ch);
typedef	objrtn	(*gSetMemoryBufferArea_t)(object self, long sz);
typedef	ifun	(*gSetMoreHandles_t)(object self, ifun fun);
typedef	objrtn	(*gSetNodeName_t)(object self, char *txt);
typedef	objrtn	(*gSetNodeValue_t)(object self, char *txt);
typedef	objrtn	(*gSetPropertyList_t)(object self, object pl);
typedef	objrtn	(*gSetTempSubDir_t)(object self, char *dir);
typedef	objrtn	(*gSetTopNode_t)(object self, object newNode);
typedef	objrtn	(*gShape_t)(object self);
typedef	short	(*gShortValue_t)(object self);
typedef	objrtn	(*gShouldNotImplement_t)(object self, char *meth);
typedef	objrtn	(*gSignal_t)(object self);
typedef	int	(*gSize_t)(object self);
typedef	objrtn	(*gSocketConnect_t)(object self, char *addr, int port, short int flag);
typedef	objrtn	(*gStackAlloc_t)(object self, void *p);
typedef	int	(*gState_t)(object self);
typedef	char *	(*gStringKey_t)(object self);
typedef	objrtn	(*gStringRep_t)(object self);
typedef	objrtn	(*gStringRepValue_t)(object self);
typedef	char *	(*gStringToXML_t)(object self, char *to, char *from);
typedef	char *	(*gStringValue_t)(object self);
typedef	objrtn	(*gStripCenter_t)(object self);
typedef	objrtn	(*gStripLeft_t)(object self);
typedef	objrtn	(*gStripRight_t)(object self);
typedef	objrtn	(*gSubClasses_t)(object self);
typedef	objrtn	(*gSubString_t)(object self, int beg, int num);
typedef	objrtn	(*gSubclassResponsibility_t)(object self, char *meth);
typedef	objrtn	(*gSuperClasses_t)(object self);
typedef	objrtn	(*gTake_t)(object self, int n);
typedef	long	(*gTimeDifference_t)(object self, object tm);
typedef	objrtn	(*gTimeStringRepValue_t)(object self);
typedef	long	(*gTimeValue_t)(object self);
typedef	int	(*gTimedRead_t)(object self, char *buf, unsigned n, int max_wait);
typedef	int	(*gTimedReadMS_t)(object self, char *buf, unsigned n, int max_wait, long microsec_wait);
typedef	int	(*gTimedWrite_t)(object self, char *buf, unsigned n, int max_wait);
typedef	objrtn	(*gToLower_t)(object self);
typedef	objrtn	(*gToUpper_t)(object self);
typedef	objrtn	(*gToday_t)(object self);
typedef	int	(*gTrace_t)(object self, int mode);
typedef	objrtn	(*gTracePrint_t)(object self, char *buf);
typedef	objrtn	(*gTruncate_t)(object self, int p);
typedef	int	(*gType_t)(object self);
typedef	int	(*gUnLock_t)(object self, unsigned long start, unsigned long len);
typedef	unsigned short	(*gUnsignedShortValue_t)(object self);
typedef	objrtn	(*gUpdateLength_t)(object self);
typedef	int	(*gValidDate_t)(object self);
typedef	int	(*gValidDateTime_t)(object self);
typedef	int	(*gValidTime_t)(object self);
typedef	objrtn	(*gValue_t)(object self);
typedef	int	(*gWaitFor_t)(object self);
typedef	objrtn	(*gWaitSemaphore_t)(object self, object sema);
typedef	int	(*gWrite_t)(object self, char *buf, unsigned len);
typedef	int	(*gWriteInt32_t)(object self, int val);
typedef	long	(*gWriteTime_t)(object self);
typedef	char *	(*gXMLToString_t)(object self, char *to, char *from);
typedef	objrtn	(*gXPath_t)(object self, char *path);
typedef	int	(*vBitValue_t)(object self, ...);
typedef	objrtn	(*vBuild_t)(object self, char *f, ...);
typedef	objrtn	(*vChangeBitValue_t)(object self, ...);
typedef	objrtn	(*vChangeCharValue_t)(object self, ...);
typedef	objrtn	(*vChangeDoubleValue_t)(object self, ...);
typedef	objrtn	(*vChangeLongValue_t)(object self, ...);
typedef	objrtn	(*vChangeShortValue_t)(object self, ...);
typedef	objrtn	(*vChangeUShortValue_t)(object self, ...);
typedef	objrtn	(*vChangeValue_t)(object self, ...);
typedef	char	(*vCharValue_t)(object self, ...);
typedef	double	(*vDoubleValue_t)(object self, ...);
typedef	objrtn	(*vError_t)(object self, ...);
typedef	objrtn	(*vGetValues_t)(object self, ...);
typedef	long	(*vLongValue_t)(object self, ...);
typedef	objrtn	(*vMakeList_t)(object self, ...);
typedef	objrtn	(*vNew_t)(object self, ...);
typedef	void *	(*vPointerValue_t)(object self, ...);
typedef	int	(*vPrintf_t)(object self, char *fmt, ...);
typedef	objrtn	(*vReshape_t)(object self, ...);
typedef	short	(*vShortValue_t)(object self, ...);
typedef	objrtn	(*vSprintf_t)(object self, char *fmt, ...);
typedef	unsigned short	(*vUnsignedShortValue_t)(object self, ...);
typedef	objrtn	(*vValue_t)(object self, ...);


#undef	END_PROTOTYPES

extern	gAccept_t	gAccept;
extern	gAdd_t	gAdd;
extern	gAddAfter_t	gAddAfter;
extern	gAddBTreeNode_t	gAddBTreeNode;
extern	gAddBefore_t	gAddBefore;
extern	gAddBodyPart_t	gAddBodyPart;
extern	gAddDays_t	gAddDays;
extern	gAddFirst_t	gAddFirst;
extern	gAddHeader_t	gAddHeader;
extern	gAddHours_t	gAddHours;
extern	gAddInt_t	gAddInt;
extern	gAddLast_t	gAddLast;
extern	gAddMilliseconds_t	gAddMilliseconds;
extern	gAddMinutes_t	gAddMinutes;
extern	gAddMonths_t	gAddMonths;
extern	gAddSeconds_t	gAddSeconds;
extern	gAddStr_t	gAddStr;
extern	gAddToPool_t	gAddToPool;
extern	gAddValue_t	gAddValue;
extern	gAddYears_t	gAddYears;
extern	gAdvance_t	gAdvance;
extern	gAlloc_t	gAlloc;
extern	gAppend_t	gAppend;
extern	gAppendChild_t	gAppendChild;
extern	gApplyMask_t	gApplyMask;
extern	gArrayPointer_t	gArrayPointer;
extern	gAttributes_t	gAttributes;
extern	gBasicSize_t	gBasicSize;
extern	gBlockingGetkey_t	gBlockingGetkey;
extern	gBufferSize_t	gBufferSize;
extern	gCalToJul_t	gCalToJul;
extern	gChangeCharAt_t	gChangeCharAt;
extern	gChangeCharValue_t	gChangeCharValue;
extern	gChangeDateTimeValues_t	gChangeDateTimeValues;
extern	gChangeDateValue_t	gChangeDateValue;
extern	gChangeDoubleValue_t	gChangeDoubleValue;
extern	gChangeFunction_t	gChangeFunction;
extern	gChangeIntKey_t	gChangeIntKey;
extern	gChangeKey_t	gChangeKey;
extern	gChangeLongValue_t	gChangeLongValue;
extern	gChangeNext_t	gChangeNext;
extern	gChangePrevious_t	gChangePrevious;
extern	gChangePriority_t	gChangePriority;
extern	gChangeRegisteredMemory_t	gChangeRegisteredMemory;
extern	gChangeShortValue_t	gChangeShortValue;
extern	gChangeStrValue_t	gChangeStrValue;
extern	gChangeStringKey_t	gChangeStringKey;
extern	gChangeTimeValue_t	gChangeTimeValue;
extern	gChangeUShortValue_t	gChangeUShortValue;
extern	gChangeValue_t	gChangeValue;
extern	gChangeValueWithInt_t	gChangeValueWithInt;
extern	gChangeValueWithObj_t	gChangeValueWithObj;
extern	gChangeValueWithStr_t	gChangeValueWithStr;
extern	gCharValue_t	gCharValue;
extern	gCharValueAt_t	gCharValueAt;
extern	gChild_t	gChild;
extern	gCompare_t	gCompare;
extern	gCompareI_t	gCompareI;
extern	gCompareN_t	gCompareN;
extern	gCompareNI_t	gCompareNI;
extern	gCopy_t	gCopy;
extern	gCount_t	gCount;
extern	gCreateAttribute_t	gCreateAttribute;
extern	gCreateCDATASection_t	gCreateCDATASection;
extern	gCreateComment_t	gCreateComment;
extern	gCreateElement_t	gCreateElement;
extern	gCreateTextNode_t	gCreateTextNode;
extern	gCurMemUsed_t	gCurMemUsed;
extern	gDateTimeDifference_t	gDateTimeDifference;
extern	gDateTimeValues_t	gDateTimeValues;
extern	gDateValue_t	gDateValue;
extern	gDayName_t	gDayName;
extern	gDeepCopy_t	gDeepCopy;
extern	gDeepDispose_t	gDeepDispose;
extern	gDeepDisposeAllNodes_t	gDeepDisposeAllNodes;
extern	gDeepDisposeFirst_t	gDeepDisposeFirst;
extern	gDeepDisposeGroup_t	gDeepDisposeGroup;
extern	gDeepDisposeInt_t	gDeepDisposeInt;
extern	gDeepDisposeLast_t	gDeepDisposeLast;
extern	gDeepDisposeObj_t	gDeepDisposeObj;
extern	gDeepDisposeStr_t	gDeepDisposeStr;
extern	gDefaultRestart_t	gDefaultRestart;
extern	gDeleteBTNode_t	gDeleteBTNode;
extern	gDifference_t	gDifference;
extern	gDispose_t	gDispose;
extern	gDispose1_t	gDispose1;
extern	gDisposeAllNodes_t	gDisposeAllNodes;
extern	gDisposeAllNodes1_t	gDisposeAllNodes1;
extern	gDisposeAttribute_t	gDisposeAttribute;
extern	gDisposeFirst_t	gDisposeFirst;
extern	gDisposeGlobalPool_t	gDisposeGlobalPool;
extern	gDisposeGroup_t	gDisposeGroup;
extern	gDisposeInt_t	gDisposeInt;
extern	gDisposeItem_t	gDisposeItem;
extern	gDisposeLast_t	gDisposeLast;
extern	gDisposeObj_t	gDisposeObj;
extern	gDisposeObject_t	gDisposeObject;
extern	gDisposePropertyList_t	gDisposePropertyList;
extern	gDisposeStr_t	gDisposeStr;
extern	gDoesNotImplement_t	gDoesNotImplement;
extern	gDontCollect_t	gDontCollect;
extern	gDoubleValue_t	gDoubleValue;
extern	gDrop_t	gDrop;
extern	gDumpMemoryDiff_t	gDumpMemoryDiff;
extern	gDumpObjects_t	gDumpObjects;
extern	gDumpObjectsDiff_t	gDumpObjectsDiff;
extern	gDumpObjectsString_t	gDumpObjectsString;
extern	gDumpXML_t	gDumpXML;
extern	gEndOfStream_t	gEndOfStream;
extern	gEnterCriticalSection_t	gEnterCriticalSection;
extern	gEqual_t	gEqual;
extern	gError_t	gError;
extern	gFileHandle_t	gFileHandle;
extern	gFind_t	gFind;
extern	gFindAdd_t	gFindAdd;
extern	gFindAddInt_t	gFindAddInt;
extern	gFindAddStr_t	gFindAddStr;
extern	gFindAddValue_t	gFindAddValue;
extern	gFindBTNEQ_t	gFindBTNEQ;
extern	gFindBTNFirst_t	gFindBTNFirst;
extern	gFindBTNGE_t	gFindBTNGE;
extern	gFindBTNGT_t	gFindBTNGT;
extern	gFindBTNLE_t	gFindBTNLE;
extern	gFindBTNLT_t	gFindBTNLT;
extern	gFindBTNLast_t	gFindBTNLast;
extern	gFindChildNode_t	gFindChildNode;
extern	gFindChildNodeWithText_t	gFindChildNodeWithText;
extern	gFindClass_t	gFindClass;
extern	gFindEQ_t	gFindEQ;
extern	gFindFirst_t	gFindFirst;
extern	gFindGE_t	gFindGE;
extern	gFindGT_t	gFindGT;
extern	gFindGeneric_t	gFindGeneric;
extern	gFindInt_t	gFindInt;
extern	gFindLE_t	gFindLE;
extern	gFindLT_t	gFindLT;
extern	gFindLast_t	gFindLast;
extern	gFindMethod_t	gFindMethod;
extern	gFindMethodObject_t	gFindMethodObject;
extern	gFindNext_t	gFindNext;
extern	gFindNextNode_t	gFindNextNode;
extern	gFindNode_t	gFindNode;
extern	gFindPrev_t	gFindPrev;
extern	gFindStr_t	gFindStr;
extern	gFindValue_t	gFindValue;
extern	gFindValueInt_t	gFindValueInt;
extern	gFindValueStr_t	gFindValueStr;
extern	gFirst_t	gFirst;
extern	gFirstAttribute_t	gFirstAttribute;
extern	gFixInvalidDate_t	gFixInvalidDate;
extern	gFlush_t	gFlush;
extern	gForAll_t	gForAll;
extern	gFormatChar_t	gFormatChar;
extern	gFormatDate_t	gFormatDate;
extern	gFormatDateTime_t	gFormatDateTime;
extern	gFormatNumber_t	gFormatNumber;
extern	gFormatTime_t	gFormatTime;
extern	gFunction_t	gFunction;
extern	gGC_t	gGC;
extern	gGCDispose_t	gGCDispose;
extern	gGetAll_t	gGetAll;
extern	gGetAttribute_t	gGetAttribute;
extern	gGetAttributeValue_t	gGetAttributeValue;
extern	gGetBodyContent_t	gGetBodyContent;
extern	gGetBodyParts_t	gGetBodyParts;
extern	gGetBoundaryString_t	gGetBoundaryString;
extern	gGetCharFromNode_t	gGetCharFromNode;
extern	gGetCipher_t	gGetCipher;
extern	gGetContentType_t	gGetContentType;
extern	gGetErrorCode_t	gGetErrorCode;
extern	gGetErrorStr_t	gGetErrorStr;
extern	gGetFloatFromNode_t	gGetFloatFromNode;
extern	gGetGenericPtr_t	gGetGenericPtr;
extern	gGetHeader_t	gGetHeader;
extern	gGetHeaders_t	gGetHeaders;
extern	gGetIntFromNode_t	gGetIntFromNode;
extern	gGetName_t	gGetName;
extern	gGetParent_t	gGetParent;
extern	gGetPeerCertificateIssuerName_t	gGetPeerCertificateIssuerName;
extern	gGetPeerCertificateSubjectName_t	gGetPeerCertificateSubjectName;
extern	gGetSessionInfo_t	gGetSessionInfo;
extern	gGetStr_t	gGetStr;
extern	gGetTotalBytesRead_t	gGetTotalBytesRead;
extern	gGets_t	gGets;
extern	gGroupRemove_t	gGroupRemove;
extern	gHash_t	gHash;
extern	gHold_t	gHold;
extern	gHours_t	gHours;
extern	gHowManyBitsOfPeerPublicKey_t	gHowManyBitsOfPeerPublicKey;
extern	gIPAddress_t	gIPAddress;
extern	gIPAddressStr_t	gIPAddressStr;
extern	gIncNelm_t	gIncNelm;
extern	gIndex_t	gIndex;
extern	gIndexOrigin_t	gIndexOrigin;
extern	gInit_t	gInit;
extern	gInitLink_t	gInitLink;
extern	gInsertBefore_t	gInsertBefore;
extern	gInsertObjAt_t	gInsertObjAt;
extern	gInstanceSize_t	gInstanceSize;
extern	gIntKey_t	gIntKey;
extern	gIntValue_t	gIntValue;
extern	gInvalidObject_t	gInvalidObject;
extern	gInvalidType_t	gInvalidType;
extern	gIota_t	gIota;
extern	gIsKindOf_t	gIsKindOf;
extern	gJulToCal_t	gJulToCal;
extern	gJulian_t	gJulian;
extern	gJustifyCenter_t	gJustifyCenter;
extern	gJustifyLeft_t	gJustifyLeft;
extern	gJustifyRight_t	gJustifyRight;
extern	gKey_t	gKey;
extern	gKill_t	gKill;
extern	gLast_t	gLast;
extern	gLeaveCriticalSection_t	gLeaveCriticalSection;
extern	gLength_t	gLength;
extern	gList_t	gList;
extern	gLoadJavaClass_t	gLoadJavaClass;
extern	gLoadMask_t	gLoadMask;
extern	gLock_t	gLock;
extern	gLongValue_t	gLongValue;
extern	gLookup_t	gLookup;
extern	gMakeServer_t	gMakeServer;
extern	gMarkMemoryBeginning_t	gMarkMemoryBeginning;
extern	gMarkObject_t	gMarkObject;
extern	gMarkRange_t	gMarkRange;
extern	gMarkingMethod_t	gMarkingMethod;
extern	gMaskFunction_t	gMaskFunction;
extern	gMaxAfterGC_t	gMaxAfterGC;
extern	gMaxMemUsed_t	gMaxMemUsed;
extern	gMilliseconds_t	gMilliseconds;
extern	gMinutes_t	gMinutes;
extern	gMode_t	gMode;
extern	gMonthName_t	gMonthName;
extern	gMoreHandles_t	gMoreHandles;
extern	gMoveAfter_t	gMoveAfter;
extern	gMoveBefore_t	gMoveBefore;
extern	gMoveBeginning_t	gMoveBeginning;
extern	gMoveEnd_t	gMoveEnd;
extern	gName_t	gName;
extern	gNew_t	gNew;
extern	gNewArray_t	gNewArray;
extern	gNewClass_t	gNewClass;
extern	gNewDateTime_t	gNewDateTime;
extern	gNewDocument_t	gNewDocument;
extern	gNewFindFile_t	gNewFindFile;
extern	gNewGeneric_t	gNewGeneric;
extern	gNewGlobalPool_t	gNewGlobalPool;
extern	gNewGlobalPoolWithSize_t	gNewGlobalPoolWithSize;
extern	gNewMethod_t	gNewMethod;
extern	gNewMimeBodyPart_t	gNewMimeBodyPart;
extern	gNewMultipartMime_t	gNewMultipartMime;
extern	gNewNode_t	gNewNode;
extern	gNewSemaphore_t	gNewSemaphore;
extern	gNewSetSeq_t	gNewSetSeq;
extern	gNewStdClass_t	gNewStdClass;
extern	gNewThread_t	gNewThread;
extern	gNewWithChar_t	gNewWithChar;
extern	gNewWithDouble_t	gNewWithDouble;
extern	gNewWithInt_t	gNewWithInt;
extern	gNewWithIntObj_t	gNewWithIntObj;
extern	gNewWithLong_t	gNewWithLong;
extern	gNewWithObj_t	gNewWithObj;
extern	gNewWithObjObj_t	gNewWithObjObj;
extern	gNewWithPtr_t	gNewWithPtr;
extern	gNewWithStr_t	gNewWithStr;
extern	gNewWithStrInt_t	gNewWithStrInt;
extern	gNewWithStrObj_t	gNewWithStrObj;
extern	gNewWithStream_t	gNewWithStream;
extern	gNewWithUnsigned_t	gNewWithUnsigned;
extern	gNext_t	gNext;
extern	gNextFile_t	gNextFile;
extern	gNow_t	gNow;
extern	gNth_t	gNth;
extern	gNumbGC_t	gNumbGC;
extern	gNumbPieces_t	gNumbPieces;
extern	gObjectChecking_t	gObjectChecking;
extern	gObjectSerialNumber_t	gObjectSerialNumber;
extern	gOpenFile_t	gOpenFile;
extern	gOpenLowFile_t	gOpenLowFile;
extern	gOpenTempFile_t	gOpenTempFile;
extern	gParent_t	gParent;
extern	gParseFile_t	gParseFile;
extern	gParseMultipartFromString_t	gParseMultipartFromString;
extern	gParseString_t	gParseString;
extern	gPiece_t	gPiece;
extern	gPointerValue_t	gPointerValue;
extern	gPop_t	gPop;
extern	gPopulateStringFromNode_t	gPopulateStringFromNode;
extern	gPosition_t	gPosition;
extern	gPrevious_t	gPrevious;
extern	gPrint_t	gPrint;
extern	gPrintLength_t	gPrintLength;
extern	gPrintValue_t	gPrintValue;
extern	gPriority_t	gPriority;
extern	gProcess_t	gProcess;
extern	gPropertyGet_t	gPropertyGet;
extern	gPropertyPut_t	gPropertyPut;
extern	gPropertyRemove_t	gPropertyRemove;
extern	gPropertySetAutoDispose_t	gPropertySetAutoDispose;
extern	gProxyConnect_t	gProxyConnect;
extern	gPush_t	gPush;
extern	gPutc_t	gPutc;
extern	gPuts_t	gPuts;
extern	gRank_t	gRank;
extern	gRead_t	gRead;
extern	gReadInt32_t	gReadInt32;
extern	gRecvFile_t	gRecvFile;
extern	gRegisterMemory_t	gRegisterMemory;
extern	gRelease_t	gRelease;
extern	gReleaseSemaphore_t	gReleaseSemaphore;
extern	gRemove_t	gRemove;
extern	gRemoveAttribute_t	gRemoveAttribute;
extern	gRemoveFirst_t	gRemoveFirst;
extern	gRemoveFromPool_t	gRemoveFromPool;
extern	gRemoveInt_t	gRemoveInt;
extern	gRemoveLast_t	gRemoveLast;
extern	gRemoveMask_t	gRemoveMask;
extern	gRemoveNode_t	gRemoveNode;
extern	gRemoveObj_t	gRemoveObj;
extern	gRemoveRegisteredMemory_t	gRemoveRegisteredMemory;
extern	gRemoveStr_t	gRemoveStr;
extern	gRemoveWaits_t	gRemoveWaits;
extern	gResize_t	gResize;
extern	gResizeMethodCache_t	gResizeMethodCache;
extern	gRetreat_t	gRetreat;
extern	gRoom_t	gRoom;
extern	gRound_t	gRound;
extern	gSaveXML_t	gSaveXML;
extern	gSeconds_t	gSeconds;
extern	gSeek_t	gSeek;
extern	gSendFile_t	gSendFile;
extern	gSendStr_t	gSendStr;
extern	gSequence_t	gSequence;
extern	gSequenceLinks_t	gSequenceLinks;
extern	gServerSocketConnect_t	gServerSocketConnect;
extern	gSetAttribute_t	gSetAttribute;
extern	gSetErrorFunction_t	gSetErrorFunction;
extern	gSetFunction_t	gSetFunction;
extern	gSetMaskFiller_t	gSetMaskFiller;
extern	gSetMemoryBufferArea_t	gSetMemoryBufferArea;
extern	gSetMoreHandles_t	gSetMoreHandles;
extern	gSetNodeName_t	gSetNodeName;
extern	gSetNodeValue_t	gSetNodeValue;
extern	gSetPropertyList_t	gSetPropertyList;
extern	gSetTempSubDir_t	gSetTempSubDir;
extern	gSetTopNode_t	gSetTopNode;
extern	gShape_t	gShape;
extern	gShortValue_t	gShortValue;
extern	gShouldNotImplement_t	gShouldNotImplement;
extern	gSignal_t	gSignal;
extern	gSize_t	gSize;
extern	gSocketConnect_t	gSocketConnect;
extern	gStackAlloc_t	gStackAlloc;
extern	gState_t	gState;
extern	gStringKey_t	gStringKey;
extern	gStringRep_t	gStringRep;
extern	gStringRepValue_t	gStringRepValue;
extern	gStringToXML_t	gStringToXML;
extern	gStringValue_t	gStringValue;
extern	gStripCenter_t	gStripCenter;
extern	gStripLeft_t	gStripLeft;
extern	gStripRight_t	gStripRight;
extern	gSubClasses_t	gSubClasses;
extern	gSubString_t	gSubString;
extern	gSubclassResponsibility_t	gSubclassResponsibility;
extern	gSuperClasses_t	gSuperClasses;
extern	gTake_t	gTake;
extern	gTimeDifference_t	gTimeDifference;
extern	gTimeStringRepValue_t	gTimeStringRepValue;
extern	gTimeValue_t	gTimeValue;
extern	gTimedRead_t	gTimedRead;
extern	gTimedReadMS_t	gTimedReadMS;
extern	gTimedWrite_t	gTimedWrite;
extern	gToLower_t	gToLower;
extern	gToUpper_t	gToUpper;
extern	gToday_t	gToday;
extern	gTrace_t	gTrace;
extern	gTracePrint_t	gTracePrint;
extern	gTruncate_t	gTruncate;
extern	gType_t	gType;
extern	gUnLock_t	gUnLock;
extern	gUnsignedShortValue_t	gUnsignedShortValue;
extern	gUpdateLength_t	gUpdateLength;
extern	gValidDate_t	gValidDate;
extern	gValidDateTime_t	gValidDateTime;
extern	gValidTime_t	gValidTime;
extern	gValue_t	gValue;
extern	gWaitFor_t	gWaitFor;
extern	gWaitSemaphore_t	gWaitSemaphore;
extern	gWrite_t	gWrite;
extern	gWriteInt32_t	gWriteInt32;
extern	gWriteTime_t	gWriteTime;
extern	gXMLToString_t	gXMLToString;
extern	gXPath_t	gXPath;
extern	vBitValue_t	vBitValue;
extern	vBuild_t	vBuild;
extern	vChangeBitValue_t	vChangeBitValue;
extern	vChangeCharValue_t	vChangeCharValue;
extern	vChangeDoubleValue_t	vChangeDoubleValue;
extern	vChangeLongValue_t	vChangeLongValue;
extern	vChangeShortValue_t	vChangeShortValue;
extern	vChangeUShortValue_t	vChangeUShortValue;
extern	vChangeValue_t	vChangeValue;
extern	vCharValue_t	vCharValue;
extern	vDoubleValue_t	vDoubleValue;
extern	vError_t	vError;
extern	vGetValues_t	vGetValues;
extern	vLongValue_t	vLongValue;
extern	vMakeList_t	vMakeList;
extern	vNew_t	vNew;
extern	vPointerValue_t	vPointerValue;
extern	vPrintf_t	vPrintf;
extern	vReshape_t	vReshape;
extern	vShortValue_t	vShortValue;
extern	vSprintf_t	vSprintf;
extern	vUnsignedShortValue_t	vUnsignedShortValue;
extern	vValue_t	vValue;



#ifdef	__cplusplus
}
#endif


#endif	/*  _GENERICS_H  */


