//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by main.rc
//
#define ID_HELP_ABOUT                   106
#define ID_WINDOW_PROPERTIES            116
#define IDR_MENU1                       130
#define DL1                             131
#define ID_CONTROLS                     132
#define ID_FILE_MESSAGE                 133
#define ALGOCORP_ICON                   134
#define ID_FILE_EXIT                    135
#define IDD_TEXT_PROPERTIES             136
#define ID_FILE_DIALOG                  137
#define IDD_STATIC_PROPERTIES           138
#define IDD_NUMERIC_PROPERTIES          139
#define IDD_DATE_PROPERTIES             140
#define IDB_EXIT                        141
#define IDD_PUSHBUTTON_PROPERTIES       142
#define IDB_CHECKBOX                    143
#define IDD_RADIOBUTTON_PROPERTIES      144
#define IDB_COMBOBOX                    145
#define IDD_CHECKBOX_PROPERTIES         146
#define IDB_DATE                        147
#define IDD_LISTBOX_PROPERTIES          148
#define IDB_LISTBOX                     149
#define IDD_COMBOBOX_PROPERTIES         150
#define IDB_NEW                         151
#define IDD_STATIC_PROPERTIES1          151
#define IDB_NUMBER                      152
#define IDB_OPEN                        153
#define IDB_PUSHBUTTON                  154
#define IDB_RADIOBUTTON                 155
#define IDB_SAVE                        156
#define IDB_STATIC                      157
#define IDB_TEST                        158
#define IDB_TEXT                        159
#define IDD_SCALE                       160
#define IDB_SCALE                       160
#define IDB_CONTROL_FONTS               161
#define IDD_CONTROL_FONTS               162
#define IDB_HandleBitmap                163
#define IDB_DragBitmap                  166
#define IDB_ALIGN_BOTTOM                172
#define IDB_ALIGN_LEFT                  173
#define IDB_ALIGN_RIGHT                 174
#define IDB_ALIGN_TOP                   175
#define IDB_CENTER_HORZ                 176
#define IDB_CENTER_VERT                 177
#define IDB_SAME_HEIGHT                 178
#define IDB_SAME_SIZE                   179
#define IDB_SAME_WIDTH                  180
#define IDB_LINE_HORZ                   183
#define IDB_RECT                        184
#define IDD_RECT_PROPERTIES             185
#define IDD_LINE_PROPERTIES             186
#define IDB_LINE_VERT                   187
#define IDB_PRINT                       188
#define IDB_PRINT_PREVIEW               189
#define IDD_PRINT                       190
#define IDB_RUN_TEST                    193
#define IDB_RULER_GRID                  194
#define IDB_COPY                        196
#define IDB_PASTE                       197
#define IDB_CUT                         198
#define IDB_UNDO                        208
#define IDR_MAIN_MENU                   210
#define IDD_ABOUT                       211
#define IDB_BARCODE                     213
#define IDB_BARCODE2                    215
#define IDB_BARCODE3                    216
#define IDD_WELCOME                     218
#define IDB_BITMAP                      220
#define IDB_LASZLO                      221
#define IDB_GENERICCONTROL              221
#define IDD_IMAGE_PROPERTIES            222
#define IDB_FLASH                       222
#define IDB_TIME                        223
#define IDD_TIME_PROPERTIES             223
#define IDD_XPATH_BINDING               224
#define IDD_WINDOW_PROPERTIES           225
#define IDD_DATAGRID_PROPERTIES         226
#define IDB_LANGSWITCH                  227
#define IDD_GENERIC_PROPERTIES          228
#define IDB_SAVEXML                     228
#define IDC_TEXT                        1000
#define IDC_CAPITALIZE                  1001
#define IDC_NUMERIC                     1002
#define IDC_CTLID                       1003
#define IDC_DATE                        1004
#define IDC_TABORDER                    1005
#define IDC_PUSHBUTTON                  1006
#define IDC_HEIGHT                      1007
#define IDC_NEW                         1008
#define IDC_WIDTH                       1009
#define IDC_LOAD                        1010
#define IDC_YPOS                        1011
#define IDC_SAVE                        1012
#define IDC_XPOS                        1013
#define IDC_MINLEN                      1014
#define IDC_MINIMUM                     1015
#define IDC_TITLE                       1016
#define IDC_RADIOBUTTON                 1017
#define IDC_MAXLEN                      1018
#define IDC_MAXIMUM                     1019
#define IDC_ONSTRING                    1020
#define IDC_NEXTID                      1021
#define IDC_CHECKBOX                    1022
#define IDC_DP                          1023
#define IDC_OFFSTRING                   1024
#define IDC_HIDE                        1025
#define IDC_LISTBOX                     1026
#define IDC_FORMAT                      1027
#define IDC_DISABLE                     1028
#define IDC_COMBOBOX                    1029
#define IDC_RIGHT                       1029
#define IDC_FIELDWIDTH                  1030
#define IDC_DISPLAYTEXT                 1031
#define IDC_TEST                        1032
#define IDC_BUTTON                      1033
#define IDC_DEFAULT                     1034
#define IDC_HELPTOPIC                   1035
#define IDC_FACTOR                      1036
#define IDC_ChangeFont                  1039
#define IDC_FontName                    1040
#define IDC_FontSize                    1041
#define IDC_StaticTextFont              1042
#define IDC_StaticTextSize              1043
#define IDC_TextFont                    1044
#define IDC_TextSize                    1045
#define IDC_NumericFont                 1046
#define IDC_NumericSize                 1047
#define IDC_DateFont                    1048
#define IDC_DateSize                    1049
#define IDC_TimeFont                    1050
#define IDC_TimeSize                    1051
#define IDC_RadioButtonFont             1052
#define IDC_RadioButtonSize             1053
#define IDC_CheckBoxFont                1054
#define IDC_CheckBoxSize                1055
#define IDC_ListBoxFont                 1056
#define IDC_ListBoxSize                 1057
#define IDC_ComboBoxFont                1058
#define IDC_ComboBoxSize                1059
#define IDC_RectControlFont             1060
#define IDC_AllControlsSize             1061
#define IDC_RectControlSize             1061
#define IDC_CBS_SIMPLE                  1062
#define IDC_PushButtonFont              1062
#define IDC_CBS_DROPDOWN                1063
#define IDC_PushButtonSize              1063
#define IDC_CBS_DROPDOWNLIST            1064
#define IDC_PATTERN_STYLE               1067
#define IDC_NO_FILL                     1068
#define IDC_FILL                        1068
#define IDC_FOREGROUND_COLOR            1069
#define IDC_LINE_COLOR                  1069
#define IDC_FRAME_LEFT                  1070
#define IDC_BACKGROUND_COLOR            1071
#define IDC_LINE_STYLE                  1071
#define IDC_FRAME_THICKNESS             1072
#define IDC_FRAME_RIGHT                 1074
#define IDC_FRAME_TOP                   1075
#define IDC_FRAME_BOTTOM                1077
#define IDC_FONT_COLOR                  1078
#define IDC_FONT                        1079
#define IDC_FONT_SIZE                   1080
#define IDC_FONT_NAME                   1081
#define IDC_RECT_LINE_COLOR             1089
#define IDC_FRAME_COLOR                 1089
#define IDC_RECT_LINE_STYLE             1090
#define IDC_DT_LEFT                     1101
#define IDC_DT_CENTER                   1102
#define IDC_DT_TOP                      1105
#define IDC_DT_VCENTER                  1106
#define IDC_DT_BOTTOM                   1107
#define IDC_DT_MULTI_LINES              1108
#define IDC_DT_RIGHT                    1111
#define IDC_3D                          1113
#define IDC_PRINT_MESSAGE               1119
#define IDC_PRINT_PAGE                  1120
#define IDC_PRINT_FILE                  1121
#define IDC_DELETE_METAFILE             1135
#define IDC_POSITION_NOCHANGE           1136
#define IDC_POSITION_FRONT              1139
#define IDC_POSITION_BACK               1140
#define IDC_SAVE_TO_META_FILE           1144
#define IDC_PRODUCT                     1145
#define IDC_VERSION                     1146
#define IDC_COPYRIGHT                   1147
#define IDC_USE_TABSTOPS                1149
#define IDC_MULTILINE                   1150
#define IDC_STATIC_WELCOME              1151
#define IDC_LOAD_BITMAP                 1159
#define IDC_CLEAR_BITMAP                1160
#define IDC_BitmapFileName              1162
#define IDC_SCROLLBAR1                  1164
#define IDC_XPATH                       1165
#define IDC_XPATH_BUTTON                1166
#define IDC_URL_COMBO                   1167
#define IDC_LIST_XPATH                  1167
#define IDC_WSDL_TREE                   1168
#define IDC_XPATH_BUTTON2               1168
#define IDC_XPATH_BUTTON_CHOICE         1168
#define IDC_RETRIEVE_BUTTON             1169
#define IDC_CHOICE_XPATH                1169
#define IDC_XPATH_BUTTON3               1170
#define IDC_WIDTH_EDIT                  1170
#define IDC_XPATH_BUTTON_LIST           1170
#define IDC_XPATH4                      1171
#define IDC_TEXT_XPATH                  1171
#define IDC_HIEGHT_EDIT                 1171
#define IDC_HEIGHT_EDIT                 1171
#define IDC_XPATH_BUTTON4               1172
#define IDC_XPATH_BUTTON_DATA           1172
#define IDC_DATA_XPATH                  1173
#define IDC_LANGUAGETEXT                1173
#define IDC_XPATH_BUTTON5               1174
#define IDC_XPATH_BUTTON_TEXT           1174
#define IDC_LANGUAGESELECT              1175
#define IDC_SAVE_PROP                   1176
#define IDC_EDIT2                       1178
#define IDC_PROP_VALUE                  1178
#define IDC_PROPERTY_COMBO              1179
#define IDC_PROPERTY_LIST               1180
#define IDC_DELETE                      1181
#define IDC_CONTROL_TYPE_NAME           1182
#define IDC_WSDLOPERATION               1183
#define IDC_BUTTON1                     1184
#define IDC_SHOWDATA                    1184
#define IDC_LOOKUP                      1184
#define IDC_PASSWORD                    1185
#define IDC_URL                         1187
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         117
#define _APS_NEXT_CONTROL_VALUE         1188
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
