/*
  Copyright (c) 1996 Blake McBride
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/



/*  This file automatically generated by dpp - do not edit  */

#define	DPP_STRATEGY	2
#define	DPP_FASTWIDE	0



#line 32 "DoubleFloatArray.d"
#include "array1.h" 

#define	CLASS	DoubleFloatArray_c
#define	ivType	DoubleFloatArray_iv_t

#include "generics.h"

object	DoubleFloatArray_c;


#line 40 "DoubleFloatArray.d"
#define TYPE double 


static gIndex_t _index; 


cvmeth objrtn DoubleFloatArray_cvm_vNew(object self, va_list _rest_)
{ 
	unsigned rank = va_arg(_rest_, unsigned);

#line 48 "DoubleFloatArray.d"
	static gNewArray_t cnew = NULL; 
	MAKE_REST(rank); 

	if (!cnew) 
		cnew = cmcPointer(Array, gNewArray); 
	return cnew(self, AT_DBLE, rank, _rest_); 
} 

#line 70 "DoubleFloatArray.c"

static	objrtn	DoubleFloatArray_cfm_vNew(object self, ...)
{
	va_list	_rest_;
	objrtn	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_cvm_vNew(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 56 "DoubleFloatArray.d"
ivmeth char DoubleFloatArray_ivm_vCharValue(object self, va_list _rest_)
{ 
	MAKE_REST(self); 
	return (char) *((TYPE *) _index(self, _rest_)); 
} 

#line 91 "DoubleFloatArray.c"

static	char	DoubleFloatArray_ifm_vCharValue(object self, ...)
{
	va_list	_rest_;
	char	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_ivm_vCharValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 62 "DoubleFloatArray.d"
ivmeth short DoubleFloatArray_ivm_vShortValue(object self, va_list _rest_)
{ 
	MAKE_REST(self); 
	return (short) *((TYPE *) _index(self, _rest_)); 
} 

#line 112 "DoubleFloatArray.c"

static	short	DoubleFloatArray_ifm_vShortValue(object self, ...)
{
	va_list	_rest_;
	short	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_ivm_vShortValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 68 "DoubleFloatArray.d"
ivmeth unsigned short DoubleFloatArray_ivm_vUnsignedShortValue(object self, va_list _rest_)
{ 
	MAKE_REST(self); 
	return (unsigned short) *((TYPE *) _index(self, _rest_)); 
} 

#line 133 "DoubleFloatArray.c"

static	unsigned short	DoubleFloatArray_ifm_vUnsignedShortValue(object self, ...)
{
	va_list	_rest_;
	unsigned short	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_ivm_vUnsignedShortValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 74 "DoubleFloatArray.d"
ivmeth long DoubleFloatArray_ivm_vLongValue(object self, va_list _rest_)
{ 
	MAKE_REST(self); 
	return (long) *((TYPE *) _index(self, _rest_)); 
} 

#line 154 "DoubleFloatArray.c"

static	long	DoubleFloatArray_ifm_vLongValue(object self, ...)
{
	va_list	_rest_;
	long	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_ivm_vLongValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 80 "DoubleFloatArray.d"
ivmeth double DoubleFloatArray_ivm_vDoubleValue(object self, va_list _rest_)
{ 
	MAKE_REST(self); 
	return (double) *((TYPE *) _index(self, _rest_)); 
} 

#line 175 "DoubleFloatArray.c"

static	double	DoubleFloatArray_ifm_vDoubleValue(object self, ...)
{
	va_list	_rest_;
	double	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_ivm_vDoubleValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 86 "DoubleFloatArray.d"
ivmeth objrtn DoubleFloatArray_ivm_vChangeValue(object self, va_list _rest_)
{ object val = va_arg(_rest_, object);
	MAKE_REST(val); 
	ChkArg(val, 2); 
	*((TYPE *) _index(self, _rest_)) = gDoubleValue(val); 
	return self; 
} 

#line 198 "DoubleFloatArray.c"

static	objrtn	DoubleFloatArray_ifm_vChangeValue(object self, ...)
{
	va_list	_rest_;
	objrtn	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_ivm_vChangeValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 94 "DoubleFloatArray.d"
ivmeth objrtn DoubleFloatArray_ivm_vChangeCharValue(object self, va_list _rest_)
{ int val = va_arg(_rest_, int);
	MAKE_REST(val); 
	*((TYPE *) _index(self, _rest_)) = (TYPE) val; 
	return self; 
} 

#line 220 "DoubleFloatArray.c"

static	objrtn	DoubleFloatArray_ifm_vChangeCharValue(object self, ...)
{
	va_list	_rest_;
	objrtn	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_ivm_vChangeCharValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 101 "DoubleFloatArray.d"
ivmeth objrtn DoubleFloatArray_ivm_vChangeShortValue(object self, va_list _rest_)
{ int val = va_arg(_rest_, int);
	MAKE_REST(val); 
	*((TYPE *) _index(self, _rest_)) = (TYPE) val; 
	return self; 
} 

#line 242 "DoubleFloatArray.c"

static	objrtn	DoubleFloatArray_ifm_vChangeShortValue(object self, ...)
{
	va_list	_rest_;
	objrtn	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_ivm_vChangeShortValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 108 "DoubleFloatArray.d"
ivmeth objrtn DoubleFloatArray_ivm_vChangeUShortValue(object self, va_list _rest_)
{ unsigned val = va_arg(_rest_, unsigned);
	MAKE_REST(val); 
	*((TYPE *) _index(self, _rest_)) = (TYPE) val; 
	return self; 
} 

#line 264 "DoubleFloatArray.c"

static	objrtn	DoubleFloatArray_ifm_vChangeUShortValue(object self, ...)
{
	va_list	_rest_;
	objrtn	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_ivm_vChangeUShortValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 115 "DoubleFloatArray.d"
ivmeth objrtn DoubleFloatArray_ivm_vChangeLongValue(object self, va_list _rest_)
{ long val = va_arg(_rest_, long);
	MAKE_REST(val); 
	*((TYPE *) _index(self, _rest_)) = (TYPE) val; 
	return self; 
} 

#line 286 "DoubleFloatArray.c"

static	objrtn	DoubleFloatArray_ifm_vChangeLongValue(object self, ...)
{
	va_list	_rest_;
	objrtn	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_ivm_vChangeLongValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 122 "DoubleFloatArray.d"
ivmeth objrtn DoubleFloatArray_ivm_vChangeDoubleValue(object self, va_list _rest_)
{ double val = va_arg(_rest_, double);
	MAKE_REST(val); 
	*((TYPE *) _index(self, _rest_)) = (TYPE) val; 
	return self; 
} 

#line 308 "DoubleFloatArray.c"

static	objrtn	DoubleFloatArray_ifm_vChangeDoubleValue(object self, ...)
{
	va_list	_rest_;
	objrtn	_ret_;
	va_start(_rest_, self);
	_ret_ = DoubleFloatArray_ivm_vChangeDoubleValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}


#line 129 "DoubleFloatArray.d"
static void init_class(void) 
{ 
	_index = imcPointer(Array, gIndex); 
} 

#line 327 "DoubleFloatArray.c"

objrtn	DoubleFloatArray_initialize(void)
{
	static  CRITICALSECTION  cs;
	static  int volatile once = 0;

	ENTERCRITICALSECTION(_CI_CS_);
	if (!once) {
		INITIALIZECRITICALSECTION(cs);
		once = 1;
	}
	LEAVECRITICALSECTION(_CI_CS_);

	ENTERCRITICALSECTION(cs);

	if (DoubleFloatArray_c) {
		LEAVECRITICALSECTION(cs);
		return DoubleFloatArray_c;
	}
	INHIBIT_THREADER;
	NumberArray_initialize();
	if (DoubleFloatArray_c)  {
		ENABLE_THREADER;
		LEAVECRITICALSECTION(cs);
		return DoubleFloatArray_c;
	}
	DoubleFloatArray_c = gNewClass(Class, "DoubleFloatArray", 0, 0, NumberArray, END);
	cvMethodFor(DoubleFloatArray, vNew, DoubleFloatArray_cvm_vNew, DoubleFloatArray_cfm_vNew);
	ivMethodFor(DoubleFloatArray, vCharValue, DoubleFloatArray_ivm_vCharValue, DoubleFloatArray_ifm_vCharValue);
	ivMethodFor(DoubleFloatArray, vChangeUShortValue, DoubleFloatArray_ivm_vChangeUShortValue, DoubleFloatArray_ifm_vChangeUShortValue);
	ivMethodFor(DoubleFloatArray, vChangeValue, DoubleFloatArray_ivm_vChangeValue, DoubleFloatArray_ifm_vChangeValue);
	ivMethodFor(DoubleFloatArray, vLongValue, DoubleFloatArray_ivm_vLongValue, DoubleFloatArray_ifm_vLongValue);
	ivMethodFor(DoubleFloatArray, vChangeCharValue, DoubleFloatArray_ivm_vChangeCharValue, DoubleFloatArray_ifm_vChangeCharValue);
	ivMethodFor(DoubleFloatArray, vUnsignedShortValue, DoubleFloatArray_ivm_vUnsignedShortValue, DoubleFloatArray_ifm_vUnsignedShortValue);
	ivMethodFor(DoubleFloatArray, vChangeDoubleValue, DoubleFloatArray_ivm_vChangeDoubleValue, DoubleFloatArray_ifm_vChangeDoubleValue);
	ivMethodFor(DoubleFloatArray, vDoubleValue, DoubleFloatArray_ivm_vDoubleValue, DoubleFloatArray_ifm_vDoubleValue);
	ivMethodFor(DoubleFloatArray, vChangeShortValue, DoubleFloatArray_ivm_vChangeShortValue, DoubleFloatArray_ifm_vChangeShortValue);
	ivMethodFor(DoubleFloatArray, vChangeLongValue, DoubleFloatArray_ivm_vChangeLongValue, DoubleFloatArray_ifm_vChangeLongValue);
	ivMethodFor(DoubleFloatArray, vShortValue, DoubleFloatArray_ivm_vShortValue, DoubleFloatArray_ifm_vShortValue);

	init_class();

	ENABLE_THREADER;

	LEAVECRITICALSECTION(cs);

	return DoubleFloatArray_c;
}



