/*
  Copyright (c) 1996 Blake McBride
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/



/*  This file automatically generated by dpp - do not edit  */

#define	DPP_STRATEGY	2
#define	DPP_FASTWIDE	0




#define	CLASS	LinkObjectSequence_c
#define	ivType	LinkObjectSequence_iv_t

#include "generics.h"

object	LinkObjectSequence_c;


#line 48 "LinkObjectSequence.c"
typedef struct  _LinkObjectSequence_iv_t  {
	object iNext;
}	LinkObjectSequence_iv_t;



#line 37 "LinkObjectSequence.d"
cmeth objrtn LinkObjectSequence_cm_gNewWithObj(object self, object link)
{ 
	object los; 
	ivType *iv; 

	ChkArgNul(link, 2); 
	los = oSuper(LinkObjectSequence_c, gNew, self)(self); 
	iv = ivPtr(los); 
	iv->iNext = link; 
	return los; 
} 

imeth objrtn LinkObjectSequence_im_gNext(object self)
{ LinkObjectSequence_iv_t *iv = GetIVs(LinkObjectSequence, self);
	object n; 
	if (n = iv->iNext) { 
		iv->iNext = gNext(iv->iNext); 
		return gValue(n); 
	} 
	return gDispose(self); 
} 


#line 79 "LinkObjectSequence.c"

objrtn	LinkObjectSequence_initialize(void)
{
	static  CRITICALSECTION  cs;
	static  int volatile once = 0;

	ENTERCRITICALSECTION(_CI_CS_);
	if (!once) {
		INITIALIZECRITICALSECTION(cs);
		once = 1;
	}
	LEAVECRITICALSECTION(_CI_CS_);

	ENTERCRITICALSECTION(cs);

	if (LinkObjectSequence_c) {
		LEAVECRITICALSECTION(cs);
		return LinkObjectSequence_c;
	}
	INHIBIT_THREADER;
	Sequence_initialize();
	if (LinkObjectSequence_c)  {
		ENABLE_THREADER;
		LEAVECRITICALSECTION(cs);
		return LinkObjectSequence_c;
	}
	LinkObjectSequence_c = gNewClass(Class, "LinkObjectSequence", sizeof(LinkObjectSequence_iv_t), 0, Sequence, END);
	cMethodFor(LinkObjectSequence, gNewWithObj, LinkObjectSequence_cm_gNewWithObj);
	iMethodFor(LinkObjectSequence, gNext, LinkObjectSequence_im_gNext);

	ENABLE_THREADER;

	LEAVECRITICALSECTION(cs);

	return LinkObjectSequence_c;
}



