/*
  Copyright (c) 1996 Blake McBride
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/



/*  This file automatically generated by dpp - do not edit  */

#define	DPP_STRATEGY	2
#define	DPP_FASTWIDE	0




#define	CLASS	LinkValue_c
#define	ivType	LinkValue_iv_t

#include "generics.h"

object	LinkValue_c;


#line 48 "LinkValue.c"
typedef struct  _LinkValue_iv_t  {
	object iValue;
}	LinkValue_iv_t;



#line 38 "LinkValue.d"
cmeth objrtn LinkValue_cm_gNewWithObj(object self, object value)
{ 
	object lnk; 
	ivType *iv; 

	ChkArgNul(value, 2); 
	lnk = oSuper(LinkValue_c, gNew, self)(self); 
	iv = ivPtr(lnk); 
	iv->iValue = value; 
	return lnk; 
} 

imeth objrtn LinkValue_im_gDeepCopy(object self)
{ LinkValue_iv_t *iv = GetIVs(LinkValue, self);
	object nobj; 

	nobj = oSuper(LinkValue_c, gDeepCopy, self)(self); 
	ivPtr(nobj)->iValue = iv->iValue ? gDeepCopy(iv->iValue) : NULL; 
	return nobj; 
} 

imeth objrtn LinkValue_im_gDeepDispose(object self)
{ LinkValue_iv_t *iv = GetIVs(LinkValue, self);
	if (iv->iValue) 
		gDeepDispose(iv->iValue); 
	return oSuper(LinkValue_c, gDeepDispose, self)(self); 
} 

imeth objrtn LinkValue_im_gValue(object self)
{ LinkValue_iv_t *iv = GetIVs(LinkValue, self);
	return iv->iValue; 
} 

imeth objrtn LinkValue_im_gChangeValue(object self, object value)
{ LinkValue_iv_t *iv = GetIVs(LinkValue, self);
	ChkArgNul(value, 2); 
	iv->iValue = value; 
	return self; 
} 

imeth objrtn LinkValue_im_gStringRepValue(object self)
{ LinkValue_iv_t *iv = GetIVs(LinkValue, self);
	return iv->iValue ? gStringRepValue(iv->iValue) : gNewWithStr(String, "(null)"); 
} 

imeth objrtn LinkValue_im_gStringRep(object self)
{ LinkValue_iv_t *iv = GetIVs(LinkValue, self);
	object a, b, s; 

	a = oSuper(LinkValue_c, gStringRepValue, self)(self); 
	b = iv->iValue ? gStringRepValue(iv->iValue) : gNewWithStr(String, "(null)"); 
	s = vBuild(String, gName(ClassOf(self)), " (", a, ", ", b, ")\n", NULL); 
	gDispose(a); 
	gDispose(b); 
	return s; 
} 


#line 114 "LinkValue.c"

objrtn	LinkValue_initialize(void)
{
	static  CRITICALSECTION  cs;
	static  int volatile once = 0;

	ENTERCRITICALSECTION(_CI_CS_);
	if (!once) {
		INITIALIZECRITICALSECTION(cs);
		once = 1;
	}
	LEAVECRITICALSECTION(_CI_CS_);

	ENTERCRITICALSECTION(cs);

	if (LinkValue_c) {
		LEAVECRITICALSECTION(cs);
		return LinkValue_c;
	}
	INHIBIT_THREADER;
	Link_initialize();
	if (LinkValue_c)  {
		ENABLE_THREADER;
		LEAVECRITICALSECTION(cs);
		return LinkValue_c;
	}
	LinkValue_c = gNewClass(Class, "LinkValue", sizeof(LinkValue_iv_t), 0, Link, END);
	cMethodFor(LinkValue, gNewWithObj, LinkValue_cm_gNewWithObj);
	iMethodFor(LinkValue, gValue, LinkValue_im_gValue);
	iMethodFor(LinkValue, gStringRepValue, LinkValue_im_gStringRepValue);
	iMethodFor(LinkValue, gChangeValue, LinkValue_im_gChangeValue);
	iMethodFor(LinkValue, gDeepDispose, LinkValue_im_gDeepDispose);
	iMethodFor(LinkValue, gStringRep, LinkValue_im_gStringRep);
	iMethodFor(LinkValue, gDeepCopy, LinkValue_im_gDeepCopy);

	ENABLE_THREADER;

	LEAVECRITICALSECTION(cs);

	return LinkValue_c;
}



