/*
  Copyright (c) 1996 Blake McBride
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/



/*  This file automatically generated by dpp - do not edit  */

#define	DPP_STRATEGY	2
#define	DPP_FASTWIDE	0



#line 32 "LongInteger.d"
#include <math.h> 

#define	CLASS	LongInteger_c
#define	ivType	LongInteger_iv_t

#include "generics.h"

object	LongInteger_c;


#line 50 "LongInteger.c"
typedef struct  _LongInteger_iv_t  {
	long iVal;
}	LongInteger_iv_t;



#line 39 "LongInteger.d"
cmeth objrtn LongInteger_cm_gNewWithLong(object self, long val)
{ 
	object obj = oSuper(LongInteger_c, gNew, self)(self); 
	ivType *iv = ivPtr(obj); 
	iv->iVal = val; 
	return(obj); 
} 

imeth int LongInteger_im_gHash(object self)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	double t; 

	t = .6125423371 * (unsigned long) iv->iVal; 
	t = t < 0.0 ? -t : t; 
	return (int) (BIG_INT * (t - floor(t))); 
} 

imeth int LongInteger_im_gCompare(object self, object obj)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	long sv, ov; 

	ChkArg(obj, 2); 
	if (ClassOf(obj) != CLASS && ClassOf(obj) != Date && ClassOf(obj) != DateTime) 
		return oSuper(LongInteger_c, gCompare, self)(self, obj); 
	if ((sv=iv->iVal) < (ov=ivPtr(obj)->iVal)) 
		return -1; 
	else if (sv == ov) 
		return 0; 
	else 
		return 1; 
} 

imeth objrtn LongInteger_im_gStringRepValue(object self)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	return vSprintf(String, "%ld", iv->iVal); 
} 

imeth char LongInteger_im_gCharValue(object self)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	return (char) iv->iVal; 
} 

imeth short LongInteger_im_gShortValue(object self)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	return (short) iv->iVal; 
} 

imeth unsigned short LongInteger_im_gUnsignedShortValue(object self)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	return (unsigned short) iv->iVal; 
} 

imeth long LongInteger_im_gLongValue(object self)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	return (long) iv->iVal; 
} 

imeth double LongInteger_im_gDoubleValue(object self)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	return (double) iv->iVal; 
} 

imeth void * LongInteger_im_gPointerValue(object self)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	return (void *) &iv->iVal; 
} 

imeth objrtn LongInteger_im_gChangeValue(object self, object val)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	ChkArg(val, 2); 
	iv->iVal = gLongValue(val); 
	return self; 
} 

imeth objrtn LongInteger_im_gChangeCharValue(object self, int val)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	iv->iVal = (long) val; 
	return self; 
} 

imeth objrtn LongInteger_im_gChangeShortValue(object self, int val)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	iv->iVal = (long) val; 
	return self; 
} 

imeth objrtn LongInteger_im_gChangeUShortValue(object self, unsigned val)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	iv->iVal = (long) val; 
	return self; 
} 

imeth objrtn LongInteger_im_gChangeLongValue(object self, long val)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	iv->iVal = (long) val; 
	return self; 
} 

imeth objrtn LongInteger_im_gChangeDoubleValue(object self, double val)
{ LongInteger_iv_t *iv = GetIVs(LongInteger, self);
	iv->iVal = (long) val; 
	return self; 
} 


#line 163 "LongInteger.c"

objrtn	LongInteger_initialize(void)
{
	static  CRITICALSECTION  cs;
	static  int volatile once = 0;

	ENTERCRITICALSECTION(_CI_CS_);
	if (!once) {
		INITIALIZECRITICALSECTION(cs);
		once = 1;
	}
	LEAVECRITICALSECTION(_CI_CS_);

	ENTERCRITICALSECTION(cs);

	if (LongInteger_c) {
		LEAVECRITICALSECTION(cs);
		return LongInteger_c;
	}
	INHIBIT_THREADER;
	Number_initialize();
	if (LongInteger_c)  {
		ENABLE_THREADER;
		LEAVECRITICALSECTION(cs);
		return LongInteger_c;
	}
	LongInteger_c = gNewClass(Class, "LongInteger", sizeof(LongInteger_iv_t), 0, Number, END);
	cMethodFor(LongInteger, gNewWithLong, LongInteger_cm_gNewWithLong);
	iMethodFor(LongInteger, gUnsignedShortValue, LongInteger_im_gUnsignedShortValue);
	iMethodFor(LongInteger, gChangeDoubleValue, LongInteger_im_gChangeDoubleValue);
	iMethodFor(LongInteger, gDoubleValue, LongInteger_im_gDoubleValue);
	iMethodFor(LongInteger, gCompare, LongInteger_im_gCompare);
	iMethodFor(LongInteger, gChangeLongValue, LongInteger_im_gChangeLongValue);
	iMethodFor(LongInteger, gChangeShortValue, LongInteger_im_gChangeShortValue);
	iMethodFor(LongInteger, gShortValue, LongInteger_im_gShortValue);
	iMethodFor(LongInteger, gPointerValue, LongInteger_im_gPointerValue);
	iMethodFor(LongInteger, gCharValue, LongInteger_im_gCharValue);
	iMethodFor(LongInteger, gStringRepValue, LongInteger_im_gStringRepValue);
	iMethodFor(LongInteger, gChangeUShortValue, LongInteger_im_gChangeUShortValue);
	iMethodFor(LongInteger, gHash, LongInteger_im_gHash);
	iMethodFor(LongInteger, gChangeValue, LongInteger_im_gChangeValue);
	iMethodFor(LongInteger, gLongValue, LongInteger_im_gLongValue);
	iMethodFor(LongInteger, gChangeCharValue, LongInteger_im_gChangeCharValue);

	ENABLE_THREADER;

	LEAVECRITICALSECTION(cs);

	return LongInteger_c;
}



