/*
  Copyright (c) 1996 Blake McBride
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/



/*  This file automatically generated by dpp - do not edit  */

#define	DPP_STRATEGY	2
#define	DPP_FASTWIDE	0



#line 32 "ObjectArray.d"
#include "array1.h" 

#define	CLASS	ObjectArray_c
#define	ivType	ObjectArray_iv_t

#include "generics.h"

object	ObjectArray_c;


#line 41 "ObjectArray.d"
#define TYPE object 


static gIndex_t _index; 


cvmeth objrtn ObjectArray_cvm_vNew(object self, va_list _rest_)
{ 
	unsigned rank = va_arg(_rest_, unsigned);

#line 49 "ObjectArray.d"
	static gNewArray_t cnew = NULL; 

	if (!cnew) 
		cnew = cmcPointer(Array, gNewArray); 
	return cnew(self, AT_OBJ, rank, _rest_); 
} 

#line 69 "ObjectArray.c"

static	objrtn	ObjectArray_cfm_vNew(object self, ...)
{
	va_list	_rest_;
	objrtn	_ret_;
	va_start(_rest_, self);
	_ret_ = ObjectArray_cvm_vNew(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 56 "ObjectArray.d"
ivmeth objrtn ObjectArray_ivm_vValue(object self, va_list _rest_)
{ 
	return *((TYPE *) _index(self, _rest_)); 
} 

#line 89 "ObjectArray.c"

static	objrtn	ObjectArray_ifm_vValue(object self, ...)
{
	va_list	_rest_;
	objrtn	_ret_;
	va_start(_rest_, self);
	_ret_ = ObjectArray_ivm_vValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}



#line 61 "ObjectArray.d"
ivmeth objrtn ObjectArray_ivm_vChangeValue(object self, va_list _rest_)
{ object val = va_arg(_rest_, object);
	ChkArgNul(val, 2); 
	*((TYPE *) _index(self, _rest_)) = val; 
	return self; 
} 

#line 111 "ObjectArray.c"

static	objrtn	ObjectArray_ifm_vChangeValue(object self, ...)
{
	va_list	_rest_;
	objrtn	_ret_;
	va_start(_rest_, self);
	_ret_ = ObjectArray_ivm_vChangeValue(self, _rest_);
	va_end(_rest_);
	return _ret_;
}


#line 68 "ObjectArray.d"
static void init_class(void) 
{ 
	_index = imcPointer(Array, gIndex); 
} 

#line 130 "ObjectArray.c"

objrtn	ObjectArray_initialize(void)
{
	static  CRITICALSECTION  cs;
	static  int volatile once = 0;

	ENTERCRITICALSECTION(_CI_CS_);
	if (!once) {
		INITIALIZECRITICALSECTION(cs);
		once = 1;
	}
	LEAVECRITICALSECTION(_CI_CS_);

	ENTERCRITICALSECTION(cs);

	if (ObjectArray_c) {
		LEAVECRITICALSECTION(cs);
		return ObjectArray_c;
	}
	INHIBIT_THREADER;
	Array_initialize();
	if (ObjectArray_c)  {
		ENABLE_THREADER;
		LEAVECRITICALSECTION(cs);
		return ObjectArray_c;
	}
	ObjectArray_c = gNewClass(Class, "ObjectArray", 0, 0, Array, END);
	cvMethodFor(ObjectArray, vNew, ObjectArray_cvm_vNew, ObjectArray_cfm_vNew);
	ivMethodFor(ObjectArray, vValue, ObjectArray_ivm_vValue, ObjectArray_ifm_vValue);
	ivMethodFor(ObjectArray, vChangeValue, ObjectArray_ivm_vChangeValue, ObjectArray_ifm_vChangeValue);

	init_class();

	ENABLE_THREADER;

	LEAVECRITICALSECTION(cs);

	return ObjectArray_c;
}



