/*
  Copyright (c) 1996 Blake McBride
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/



/*  This file automatically generated by dpp - do not edit  */

#define	DPP_STRATEGY	2
#define	DPP_FASTWIDE	0



#line 33 "ShortArray.d"
#include "array1.h" 

#define	CLASS	ShortArray_c
#define	ivType	ShortArray_iv_t

#include "generics.h"

object	ShortArray_c;


#line 41 "ShortArray.d"
#define TYPE short 


static gIndex_t _index; 


cvmeth objrtn ShortArray_cvm_vNew(object self, va_list _rest_)
{ 
	unsigned rank = va_arg(_rest_, unsigned);

#line 49 "ShortArray.d"
	static gNewArray_t cnew = NULL; 
	MAKE_REST(rank); 

	if (!cnew) 
		cnew = cmcPointer(Array, gNewArray); 
	return cnew(self, AT_SHRT, rank, _rest_); 
} 

#line 70 "ShortArray.c"

static	objrtn	ShortArray_cfm_vNew(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_cvm_vNew(self, _rest_);
}



#line 57 "ShortArray.d"
ivmeth char ShortArray_ivm_vCharValue(object self, va_list _rest_)
{ 
	MAKE_REST(self); 
	return (char) *((TYPE *) _index(self, _rest_)); 
} 

#line 88 "ShortArray.c"

static	char	ShortArray_ifm_vCharValue(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_ivm_vCharValue(self, _rest_);
}



#line 63 "ShortArray.d"
ivmeth short ShortArray_ivm_vShortValue(object self, va_list _rest_)
{ 
	MAKE_REST(self); 
	return (short) *((TYPE *) _index(self, _rest_)); 
} 

#line 106 "ShortArray.c"

static	short	ShortArray_ifm_vShortValue(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_ivm_vShortValue(self, _rest_);
}



#line 69 "ShortArray.d"
ivmeth unsigned short ShortArray_ivm_vUnsignedShortValue(object self, va_list _rest_)
{ 
	MAKE_REST(self); 
	return (unsigned short) *((TYPE *) _index(self, _rest_)); 
} 

#line 124 "ShortArray.c"

static	unsigned short	ShortArray_ifm_vUnsignedShortValue(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_ivm_vUnsignedShortValue(self, _rest_);
}



#line 75 "ShortArray.d"
ivmeth long ShortArray_ivm_vLongValue(object self, va_list _rest_)
{ 
	MAKE_REST(self); 
	return (long) *((TYPE *) _index(self, _rest_)); 
} 

#line 142 "ShortArray.c"

static	long	ShortArray_ifm_vLongValue(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_ivm_vLongValue(self, _rest_);
}



#line 81 "ShortArray.d"
ivmeth double ShortArray_ivm_vDoubleValue(object self, va_list _rest_)
{ 
	MAKE_REST(self); 
	return (double) *((TYPE *) _index(self, _rest_)); 
} 

#line 160 "ShortArray.c"

static	double	ShortArray_ifm_vDoubleValue(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_ivm_vDoubleValue(self, _rest_);
}



#line 87 "ShortArray.d"
ivmeth objrtn ShortArray_ivm_vChangeValue(object self, va_list _rest_)
{ object val = va_arg(_rest_, object);
	MAKE_REST(val); 
	ChkArg(val, 2); 
	*((TYPE *) _index(self, _rest_)) = gShortValue(val); 
	return self; 
} 

#line 180 "ShortArray.c"

static	objrtn	ShortArray_ifm_vChangeValue(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_ivm_vChangeValue(self, _rest_);
}



#line 95 "ShortArray.d"
ivmeth objrtn ShortArray_ivm_vChangeCharValue(object self, va_list _rest_)
{ int val = va_arg(_rest_, int);
	MAKE_REST(val); 
	*((TYPE *) _index(self, _rest_)) = (TYPE) val; 
	return self; 
} 

#line 199 "ShortArray.c"

static	objrtn	ShortArray_ifm_vChangeCharValue(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_ivm_vChangeCharValue(self, _rest_);
}



#line 102 "ShortArray.d"
ivmeth objrtn ShortArray_ivm_vChangeShortValue(object self, va_list _rest_)
{ int val = va_arg(_rest_, int);
	MAKE_REST(val); 
	*((TYPE *) _index(self, _rest_)) = (TYPE) val; 
	return self; 
} 

#line 218 "ShortArray.c"

static	objrtn	ShortArray_ifm_vChangeShortValue(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_ivm_vChangeShortValue(self, _rest_);
}



#line 109 "ShortArray.d"
ivmeth objrtn ShortArray_ivm_vChangeUShortValue(object self, va_list _rest_)
{ unsigned val = va_arg(_rest_, unsigned);
	MAKE_REST(val); 
	*((TYPE *) _index(self, _rest_)) = (TYPE) val; 
	return self; 
} 

#line 237 "ShortArray.c"

static	objrtn	ShortArray_ifm_vChangeUShortValue(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_ivm_vChangeUShortValue(self, _rest_);
}



#line 116 "ShortArray.d"
ivmeth objrtn ShortArray_ivm_vChangeLongValue(object self, va_list _rest_)
{ long val = va_arg(_rest_, long);
	MAKE_REST(val); 
	*((TYPE *) _index(self, _rest_)) = (TYPE) val; 
	return self; 
} 

#line 256 "ShortArray.c"

static	objrtn	ShortArray_ifm_vChangeLongValue(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_ivm_vChangeLongValue(self, _rest_);
}



#line 123 "ShortArray.d"
ivmeth objrtn ShortArray_ivm_vChangeDoubleValue(object self, va_list _rest_)
{ double val = va_arg(_rest_, double);
	MAKE_REST(val); 
	*((TYPE *) _index(self, _rest_)) = (TYPE) val; 
	return self; 
} 

#line 275 "ShortArray.c"

static	objrtn	ShortArray_ifm_vChangeDoubleValue(object self, ...)
{
	va_list	_rest_;
	va_start(_rest_, self);
	return ShortArray_ivm_vChangeDoubleValue(self, _rest_);
}


#line 130 "ShortArray.d"
static void init_class(void) 
{ 
	_index = imcPointer(Array, gIndex); 
} 

#line 291 "ShortArray.c"

objrtn	ShortArray_initialize(void)
{
	static  CRITICALSECTION  cs;
	static  int volatile once = 0;

	ENTERCRITICALSECTION(_CI_CS_);
	if (!once) {
		INITIALIZECRITICALSECTION(cs);
		once = 1;
	}
	LEAVECRITICALSECTION(_CI_CS_);

	ENTERCRITICALSECTION(cs);

	if (ShortArray_c) {
		LEAVECRITICALSECTION(cs);
		return ShortArray_c;
	}
	INHIBIT_THREADER;
	NumberArray_initialize();
	if (ShortArray_c)  {
		ENABLE_THREADER;
		LEAVECRITICALSECTION(cs);
		return ShortArray_c;
	}
	ShortArray_c = gNewClass(Class, "ShortArray", 0, 0, NumberArray, END);
	cvMethodFor(ShortArray, vNew, ShortArray_cvm_vNew, ShortArray_cfm_vNew);
	ivMethodFor(ShortArray, vCharValue, ShortArray_ivm_vCharValue, ShortArray_ifm_vCharValue);
	ivMethodFor(ShortArray, vChangeUShortValue, ShortArray_ivm_vChangeUShortValue, ShortArray_ifm_vChangeUShortValue);
	ivMethodFor(ShortArray, vChangeValue, ShortArray_ivm_vChangeValue, ShortArray_ifm_vChangeValue);
	ivMethodFor(ShortArray, vLongValue, ShortArray_ivm_vLongValue, ShortArray_ifm_vLongValue);
	ivMethodFor(ShortArray, vChangeCharValue, ShortArray_ivm_vChangeCharValue, ShortArray_ifm_vChangeCharValue);
	ivMethodFor(ShortArray, vUnsignedShortValue, ShortArray_ivm_vUnsignedShortValue, ShortArray_ifm_vUnsignedShortValue);
	ivMethodFor(ShortArray, vChangeDoubleValue, ShortArray_ivm_vChangeDoubleValue, ShortArray_ifm_vChangeDoubleValue);
	ivMethodFor(ShortArray, vDoubleValue, ShortArray_ivm_vDoubleValue, ShortArray_ifm_vDoubleValue);
	ivMethodFor(ShortArray, vChangeShortValue, ShortArray_ivm_vChangeShortValue, ShortArray_ifm_vChangeShortValue);
	ivMethodFor(ShortArray, vChangeLongValue, ShortArray_ivm_vChangeLongValue, ShortArray_ifm_vChangeLongValue);
	ivMethodFor(ShortArray, vShortValue, ShortArray_ivm_vShortValue, ShortArray_ifm_vShortValue);

	init_class();

	ENABLE_THREADER;

	LEAVECRITICALSECTION(cs);

	return ShortArray_c;
}



