/*
  Copyright (c) 1996 Blake McBride
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  1. Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/



/*  This file automatically generated by dpp - do not edit  */

#define	DPP_STRATEGY	2
#define	DPP_FASTWIDE	0




#define	CLASS	StackTracer_c
#define	ivType	StackTracer_iv_t

#include "generics.h"

object	StackTracer_c;


#line 48 "StackTracer.c"
typedef struct  _StackTracer_iv_t  {
	object iLogger;
	int iDisplayOn;
	int iLogOn;
	int ( * iFunction ) ( );
	object iErrorMessage;
	object iStackDumpText;
	int iFake;
	int iShowUsage;
	int iNskip;
}	StackTracer_iv_t;


#line 62 "StackTracer.c"
typedef struct  _StackTracer_cv_t  {
	object cTracer;
	char cAppName [ 255 ];
	int cOutputMode;
}	StackTracer_cv_t;

static	StackTracer_cv_t	*StackTracer_cv;


#line 26 "StackTracer.d"
#include <stdio.h> 
#include <sys/wait.h> 
#ifdef __linux__ 
#include <sys/prctl.h> 
#endif 


#line 31 "StackTracer.d"
#include <unistd.h> 
#include <sys/types.h> 
#include <sys/stat.h> 
#include <fcntl.h> 
#include <time.h> 
#include <string.h> 
#include <stdlib.h> 

#define IGNORE_RETURN (void)! 

static int command_line_error_handler(char *msg); 
static void print_trace(object logger); 

#define MIN_SIZE 60000 
#define MAX_SIZE 1000000 


imeth void StackTracer_im_gLogMessage(object self, char *pszMessage)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	int h; 

	if (!iv->iLogOn) 
		return; 
	LOG_INFO(iv->iLogger, pszMessage); 
} 

cmeth void StackTracer_cm_gLogMessage(object self, char *msg)
{ 
	gLogMessage(StackTracer_cv->cTracer, msg); 
} 

static void init_class() 
{ 
	char *v = getenv("DEBUG_OUTPUT_MODE"); 

	if (!v || !*v) 
		StackTracer_cv->cOutputMode = 1; 
	else 
		StackTracer_cv->cOutputMode = *v - '0'; 

	StackTracer_cv->cTracer = gNew(StackTracer); 

	gSetErrorFunction(Object, command_line_error_handler); 
} 

imeth objrtn StackTracer_im_gSetLogger(object self, object logger)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	iv->iLogger = logger; 
	return self; 
} 

imeth void StackTracer_im_gSetLogOn(object self, int bOn)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	iv->iLogOn = bOn; 
} 

imeth void StackTracer_im_gSetDisplayOn(object self, int bOn)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	iv->iDisplayOn = bOn; 
} 

imeth int StackTracer_im_gIsLogOn(object self)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	return iv->iLogOn; 
} 

imeth int StackTracer_im_gIsDisplayOn(object self)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	return iv->iDisplayOn; 
} 

imeth objrtn StackTracer_im_gGetLogFileName(object self)
{ 
	return gNewWithStr(String, ""); 
} 

cmeth objrtn StackTracer_cm_gGetTracer(object self)
{ 
	return StackTracer_cv->cTracer; 
} 

cmeth objrtn StackTracer_cm_gNewWithLogger(object self, object logger)
{ 
	object obj = oSuper(StackTracer_c, gNew, self)(self); 
	ivType *iv = ivPtr(obj); 

	iv->iDisplayOn = 0; 
	iv->iLogOn = 1; 

	iv->iNskip = 4; 
	iv->iShowUsage = 1; 

	iv->iLogger = logger; 

	return obj; 
} 

imeth objrtn StackTracer_im_gDispose(object self)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	if (IsObj((object)iv->iFunction)) 
		gDispose((object)iv->iFunction); 
	if (IsObj(iv->iErrorMessage)) 
		gDispose(iv->iErrorMessage); 
	if (IsObj(iv->iStackDumpText)) 
		gDispose(iv->iStackDumpText); 
	return oSuper(StackTracer_c, gDispose, self)(self); 
} 

static int command_line_error_handler(char *msg) 
{ 
	gStackDump(gGetTracer(StackTracer), msg); 
	return 0; 
} 

imeth ofun StackTracer_im_gSetFunction(object self, int (*fun)())
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	ofun ret = (ofun) iv->iFunction; 
	iv->iFunction = fun; 
	return ret; 
} 

imeth objrtn StackTracer_im_gGetStackDumpText(object self)
{ 
	return gNewWithStr(String, "Method not available."); 
} 

imeth char * StackTracer_im_gGetStackDumpString(object self)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	if (IsObj(iv->iStackDumpText)) 
		return gStringValue(iv->iStackDumpText); 
	return ""; 
} 

imeth char * StackTracer_im_gGetErrorMessage(object self)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	if (IsObj(iv->iErrorMessage)) 
		return gStringValue(iv->iErrorMessage); 
	return ""; 
} 

imeth void StackTracer_im_gStackDump(object self, char *pszMessage)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	char szText[64000]; 
	int h; 
	time_t tb; 
	struct tm *ts; 
	time(&tb); 
	ts = localtime(&tb); 

	iv->iErrorMessage = gNewWithStr(String, pszMessage); 

	sprintf(szText, "// =====================================================\nDateTime: %d-%02d-%02d %2d:%02d\nAppName: %s\n\n", 1900 + ts->tm_year, 1 + ts->tm_mon, ts->tm_mday, ts->tm_hour, ts->tm_min, StackTracer_cv->cAppName); 

	if (pszMessage) { 
		strcat(szText, pszMessage); 
		strcat(szText, "\n\n"); 
	} 
	LOG_INFO(iv->iLogger, szText); 
	print_trace(iv->iLogger); 
} 

cmeth void StackTracer_cm_gStackDump(object self, char *pszMessage)
{ 
	gStackDump(StackTracer_cv->cTracer, pszMessage); 
} 

PMETHOD void pShowUsage(object self, int flg)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	iv->iShowUsage = flg; 
} 

cmeth void StackTracer_cm_gShowUsage(object self, int flg)
{ 
	pShowUsage(StackTracer_cv->cTracer, flg); 
} 

PMETHOD void pTraceCall(object self)
{ StackTracer_iv_t *iv = GetIVs(StackTracer, self);
	if (iv->iShowUsage) { 
		int nskip = iv->iNskip; 
		iv->iNskip = 5; 
		gStackDump(StackTracer_cv->cTracer, "TRACE"); 
		iv->iNskip = nskip; 
	} 
} 

cmeth void StackTracer_cm_gTraceCall(object self)
{ 
	pTraceCall(StackTracer_cv->cTracer); 
} 

static void print_trace(object logger) 
{ 
	int fh = gOpenLogFile(logger); 
	char pid_buf[30]; 
	sprintf(pid_buf, "%d", getpid()); 
	char name_buf[512]; 
	name_buf[readlink("/proc/self/exe", name_buf, 511)]=0; 
#ifdef __linux__ 
	prctl(PR_SET_PTRACER, PR_SET_PTRACER_ANY, 0, 0, 0); 
#endif 


#line 232 "StackTracer.d"
	int child_pid = fork(); 
	if (!child_pid) { 
		dup2(fh, 1); 
		dup2(fh, 2); 
		execl("/usr/bin/gdb", "gdb", "--batch", "-n", "-ex", "thread", "-ex", "bt", name_buf, pid_buf, NULL); 
		abort(); 
	} else { 
		waitpid(child_pid, NULL, 0); 
		gCloseLogFile(logger, fh); 
	} 
} 

#line 297 "StackTracer.c"

objrtn	StackTracer_initialize(void)
{
	static  CRITICALSECTION  cs;
	static  int volatile once = 0;

	ENTERCRITICALSECTION(_CI_CS_);
	if (!once) {
		INITIALIZECRITICALSECTION(cs);
		once = 1;
	}
	LEAVECRITICALSECTION(_CI_CS_);

	ENTERCRITICALSECTION(cs);

	if (StackTracer_c) {
		LEAVECRITICALSECTION(cs);
		return StackTracer_c;
	}
	INHIBIT_THREADER;
	StackTracer_c = gNewClass(Class, "StackTracer", sizeof(StackTracer_iv_t), sizeof(StackTracer_cv_t), END);
	cMethodFor(StackTracer, gStackDump, StackTracer_cm_gStackDump);
	cMethodFor(StackTracer, gNewWithLogger, StackTracer_cm_gNewWithLogger);
	cMethodFor(StackTracer, gGetTracer, StackTracer_cm_gGetTracer);
	cMethodFor(StackTracer, gTraceCall, StackTracer_cm_gTraceCall);
	cMethodFor(StackTracer, gLogMessage, StackTracer_cm_gLogMessage);
	cMethodFor(StackTracer, gShowUsage, StackTracer_cm_gShowUsage);
	iMethodFor(StackTracer, gStackDump, StackTracer_im_gStackDump);
	iMethodFor(StackTracer, gSetFunction, StackTracer_im_gSetFunction);
	iMethodFor(StackTracer, gSetDisplayOn, StackTracer_im_gSetDisplayOn);
	iMethodFor(StackTracer, gGetStackDumpString, StackTracer_im_gGetStackDumpString);
	iMethodFor(StackTracer, gIsLogOn, StackTracer_im_gIsLogOn);
	iMethodFor(StackTracer, gGetLogFileName, StackTracer_im_gGetLogFileName);
	iMethodFor(StackTracer, gSetLogOn, StackTracer_im_gSetLogOn);
	iMethodFor(StackTracer, gGetErrorMessage, StackTracer_im_gGetErrorMessage);
	iMethodFor(StackTracer, gDispose, StackTracer_im_gDispose);
	iMethodFor(StackTracer, gGetStackDumpText, StackTracer_im_gGetStackDumpText);
	iMethodFor(StackTracer, gLogMessage, StackTracer_im_gLogMessage);
	iMethodFor(StackTracer, gSetLogger, StackTracer_im_gSetLogger);
	iMethodFor(StackTracer, gDeepDispose, StackTracer_im_gDispose);
	iMethodFor(StackTracer, gIsDisplayOn, StackTracer_im_gIsDisplayOn);

	StackTracer_cv = GetCVs(StackTracer);

	init_class();

	ENABLE_THREADER;

	LEAVECRITICALSECTION(cs);

	return StackTracer_c;
}



